"""added columns to hold input and output cost per million tokens

Revision ID: 95e47bd0fdb4
Revises: f40efe22faef
Create Date: 2024-09-12 06:13:22.021709+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '95e47bd0fdb4'
down_revision: str | None = 'f40efe22faef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_model_provider_associations', sa.Column('input_cost_usd_per_million_tokens', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('language_model_provider_associations', sa.Column('output_cost_usd_per_million_tokens', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_model_provider_associations', 'output_cost_usd_per_million_tokens')
    op.drop_column('language_model_provider_associations', 'input_cost_usd_per_million_tokens')
    # ### end Alembic commands ###
