"""added 3 additional columns to hold parameter, context window and knowledge cutoff data

Revision ID: 169638571e3a
Revises: 5bc7b317f2fc
Create Date: 2024-09-10 11:15:47.388588+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '169638571e3a'
down_revision: str | None = '5bc7b317f2fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('parameter_count', sa.Numeric(precision=15, scale=0), nullable=True))
    op.add_column('language_models', sa.Column('context_window_tokens', sa.Numeric(precision=15, scale=0), nullable=True))
    op.add_column('language_models', sa.Column('knowledge_cutoff_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_models', 'knowledge_cutoff_date')
    op.drop_column('language_models', 'context_window_tokens')
    op.drop_column('language_models', 'parameter_count')
    # ### end Alembic commands ###
