"""mark chat_message abstract

Revision ID: 71bac2669557
Revises: d5cfe1dc3120
Create Date: 2024-08-09 23:41:50.601409+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '71bac2669557'
down_revision: str | None = 'd5cfe1dc3120'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'messagetype', ['USER_MESSAGE', 'ASSISTANT_MESSAGE'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='message_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'messagetype', ['CHAT_MESSAGE', 'USER_MESSAGE', 'ASSISTANT_MESSAGE'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='message_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
