"""Use int64 instead of numeric for parameter count and context window

Revision ID: 311434a373e4
Revises: 169638571e3a
Create Date: 2024-09-11 11:06:13.609934+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '311434a373e4'
down_revision: str | None = '169638571e3a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_models', 'parameter_count',
               existing_type=sa.NUMERIC(precision=15, scale=0),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('language_models', 'context_window_tokens',
               existing_type=sa.NUMERIC(precision=15, scale=0),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_models', 'context_window_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=15, scale=0),
               existing_nullable=True)
    op.alter_column('language_models', 'parameter_count',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=15, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
