"""Add quick-response-message as subclass of assistant message

Revision ID: bbb0c0af1ace
Revises: c6c919d58965
Create Date: 2024-08-23 23:53:57.220947+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'bbb0c0af1ace'
down_revision: str | None = 'c6c919d58965'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'messagetype', ['USER_MESSAGE', 'ASSISTANT_MESSAGE', 'QUICK_RESPONSE_MESSAGE'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='message_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'messagetype', ['USER_MESSAGE', 'ASSISTANT_MESSAGE'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='message_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
