"""Add user-chat foreign key

Revision ID: 6603078f1072
Revises: 71bac2669557
Create Date: 2024-08-12 17:49:30.551838+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6603078f1072'
down_revision: str | None = '71bac2669557'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('creator_user_id', sa.Text(), nullable=False))
    op.create_foreign_key('chat_creator_user_id_fkey', 'chats', 'users', ['creator_user_id'], ['id'])
    op.add_column('turns', sa.Column('creator_user_id', sa.Text(), nullable=False))
    op.create_foreign_key('turn_creator_user_id_fkey', 'turns', 'users', ['creator_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('turn_creator_user_id_fkey', 'turns', type_='foreignkey')
    op.drop_column('turns', 'creator_user_id')
    op.drop_constraint('chat_creator_user_id_fkey', 'chats', type_='foreignkey')
    op.drop_column('chats', 'creator_user_id')
    # ### end Alembic commands ###
