"""added organization table

Revision ID: b2815eed8da2
Revises: 311434a373e4
Create Date: 2024-09-11 15:52:17.327928+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b2815eed8da2'
down_revision: str | None = '311434a373e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_organization_name'), 'organizations', ['organization_name'], unique=True)
    op.add_column('language_models', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'language_models', 'organizations', ['organization_id'], ['organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language_models', type_='foreignkey')
    op.drop_column('language_models', 'organization_id')
    op.drop_index(op.f('ix_organizations_organization_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
