"""rename model_id to language_model_id

Revision ID: 238a41c46089
Revises: ff3537d3773c
Create Date: 2024-09-08 15:49:07.637782+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '238a41c46089'
down_revision: str | None = 'ff3537d3773c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_models', 'model_id', new_column_name='language_model_id')
    op.alter_column('ratings', 'model_id', new_column_name='language_model_id')
    op.alter_column('ratings_history', 'model_id', new_column_name='language_model_id')

    op.execute('ALTER INDEX uq_model_category RENAME TO uq_language_model_category')
    op.execute('ALTER INDEX uq_model_category_created_at RENAME TO uq_language_model_category_created_at')
    op.execute('ALTER TABLE ratings RENAME CONSTRAINT ratings_model_id_fkey TO ratings_language_model_id_fkey')
    op.execute('ALTER TABLE ratings_history RENAME CONSTRAINT ratings_history_model_id_fkey TO ratings_history_language_model_id_fkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_models', 'language_model_id', new_column_name='model_id')
    op.alter_column('ratings', 'language_model_id', new_column_name='model_id')
    op.alter_column('ratings_history', 'language_model_id', new_column_name='model_id')

    op.execute('ALTER INDEX uq_language_model_category RENAME TO uq_model_category')
    op.execute('ALTER INDEX uq_language_model_category_created_at RENAME TO uq_model_category_created_at')
    op.execute('ALTER TABLE ratings RENAME CONSTRAINT ratings_language_model_id_fkey TO ratings_model_id_fkey')
    op.execute('ALTER TABLE ratings_history RENAME CONSTRAINT ratings_history_language_model_id_fkey TO ratings_history_model_id_fkey')
    # ### end Alembic commands ###
