FROM gcr.io/yupp-llms/backend-base:latest

# set work directory
WORKDIR /app/

ENV PYTHONPATH=/app

# Copy application code and data
COPY ./ypl/ /app/ypl/
COPY ./data/ /app/data/
COPY ./.env /app/.env

RUN chmod +x /app/ypl/webhooks/entrypoint.sh

ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["/app/ypl/webhooks/entrypoint.sh"] 