FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install poetry==1.8.2 && \
    poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root --no-dev --no-cache && \
    rm -rfv /root/.cache/

COPY . .
RUN chmod +x /app/ypl/webhooks/entrypoint.sh

ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["/app/ypl/webhooks/entrypoint.sh"] 