#!/bin/bash

git add .
if [ $# -eq 0 ]; then
    read -p "Enter commit message (default: WIP): " message
    if [ -z "$message" ]; then
        git commit -m "WIP"
    else
        git commit -m "$message"
    fi
else
    # Join all arguments with spaces to form the commit message
    commit_message="$*"
    git commit -m "$commit_message"
fi
