"""Remove PROMPT from RewardActionLog.ActionType

Revision ID: 33a3f2b716ec
Revises: 6fc1d7c7fa27
Create Date: 2024-12-23 10:44:09.077121+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '33a3f2b716ec'
down_revision: str | None = '6fc1d7c7fa27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'pointsactionenum', ['UNKNOWN', 'PROMPT', 'REWARD', 'CASHOUT', 'ADJUSTMENT', 'EVALUATION', 'SIGN_UP'],
                        [TableReference(table_schema='public', table_name='point_transactions', column_name='action_type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'EVALUATION', 'QT_EVAL', 'TURN', 'FEEDBACK', 'MODEL_FEEDBACK'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type'), TableReference(table_schema='public', table_name='reward_amount_rules', column_name='action_type', existing_server_default="'TURN'::rewardactionenum"), TableReference(table_schema='public', table_name='reward_probability_rules', column_name='action_type', existing_server_default="'TURN'::rewardactionenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'PROMPT', 'EVALUATION', 'QT_EVAL', 'TURN', 'FEEDBACK', 'MODEL_FEEDBACK'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type'), TableReference(table_schema='public', table_name='reward_amount_rules', column_name='action_type', existing_server_default="'TURN'::rewardactionenum"), TableReference(table_schema='public', table_name='reward_probability_rules', column_name='action_type', existing_server_default="'TURN'::rewardactionenum")],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'pointsactionenum', ['UNKNOWN', 'SIGN_UP', 'REWARD', 'CASHOUT', 'ADJUSTMENT', 'PROMPT', 'EVALUATION'],
                        [TableReference(table_schema='public', table_name='point_transactions', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
