"""add turn quality

Revision ID: 6c3ca630eec7
Revises: 7df7107cf593
Create Date: 2024-10-02 18:11:26.893940+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6c3ca630eec7'
down_revision: str | None = '7df7107cf593'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turn_qualities',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('turn_quality_id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('prompt_difficulty', sa.Float(), nullable=True),
    sa.Column('prompt_novelty', sa.Float(), nullable=True),
    sa.Column('turn_contribution', sa.Float(), nullable=True),
    sa.Column('prompt_difficulty_judge_model_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_difficulty_judge_model_id'], ['language_models.language_model_id'], name=op.f('fk_turn_qualities_prompt_difficulty_judge_model_id_language_models')),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], name=op.f('fk_turn_qualities_turn_id_turns')),
    sa.PrimaryKeyConstraint('turn_quality_id', name=op.f('pk_turn_qualities')),
    sa.UniqueConstraint('turn_id', name=op.f('uq_turn_qualities_turn_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn_qualities')
    # ### end Alembic commands ###
