"""adding a new enum called feedback to RewardActionEnum

Revision ID: 860508bf689b
Revises: e4ed0bc903f0
Create Date: 2024-12-04 15:01:43.088512+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '860508bf689b'
down_revision: str | None = 'e4ed0bc903f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'PROMPT', 'EVALUATION', 'TURN', 'FEEDBACK'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'PROMPT', 'EVALUATION', 'TURN'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
