"""Remove LMPA

Revision ID: fada3bdd7de2
Revises: fc4ad9dd509e
Create Date: 2024-10-14 06:44:13.707735+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fada3bdd7de2'
down_revision: str | None = 'fc4ad9dd509e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_model_provider_associations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_model_provider_associations',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('language_model_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('input_cost_usd_per_million_tokens', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('output_cost_usd_per_million_tokens', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('provider_specific_model_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['language_model_id'], ['language_models.language_model_id'], name='language_model_provider_associations_language_model_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name='language_model_provider_associations_provider_id_fkey'),
    sa.PrimaryKeyConstraint('language_model_id', 'provider_id', name='pk_language_model_provider_associations')
    )
    # ### end Alembic commands ###
