"""Add is_pro to language_models table

Revision ID: 1436fbf4f3b6
Revises: 495367cf8ece
Create Date: 2024-11-19 22:40:00.813260+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1436fbf4f3b6'
down_revision: str | None = '495367cf8ece'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('is_pro', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_language_models_is_pro'), 'language_models', ['is_pro'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_models_is_pro'), table_name='language_models')
    op.drop_column('language_models', 'is_pro')
    # ### end Alembic commands ###
