"""Add semantic group column

Revision ID: 15add8650730
Revises: 0f7d4a848bf0
Create Date: 2024-12-12 21:05:02.733202+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '15add8650730'
down_revision: str | None = '0f7d4a848bf0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('semantic_group', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_language_models_semantic_group'), 'language_models', ['semantic_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_models_semantic_group'), table_name='language_models')
    op.drop_column('language_models', 'semantic_group')
    # ### end Alembic commands ###
