"""adding an index to action_type

Revision ID: 2f11762adef7
Revises: 38eb10ab835c
Create Date: 2024-12-05 11:41:06.311455+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2f11762adef7'
down_revision: str | None = '38eb10ab835c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reward_action_logs_action_type'), 'reward_action_logs', ['action_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_action_logs_action_type'), table_name='reward_action_logs')
    # ### end Alembic commands ###
