"""add assistant model selection source to chat messages

Revision ID: 7850ee216b6b
Revises: 5fdf565a327c
Create Date: 2024-10-28 18:53:27.373722+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7850ee216b6b'
down_revision: str | None = '5fdf565a327c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('UNKNOWN', 'USER_SELECTED', 'ROUTER_SELECTED', 'QUICK_TAKE_DEFAULT', name='assistantselectionsource').create(op.get_bind())
    op.add_column('chat_messages', sa.Column('assistant_selection_source', postgresql.ENUM('UNKNOWN', 'USER_SELECTED', 'ROUTER_SELECTED', 'QUICK_TAKE_DEFAULT', name='assistantselectionsource', create_type=False), server_default='UNKNOWN', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'assistant_selection_source')
    sa.Enum('UNKNOWN', 'USER_SELECTED', 'ROUTER_SELECTED', 'QUICK_TAKE_DEFAULT', name='assistantselectionsource').drop(op.get_bind())
    # ### end Alembic commands ###
