"""add cbbtc as an enum

Revision ID: cc15858d489d
Revises: 33a3f2b716ec
Create Date: 2024-12-24 15:01:03.635160+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'cc15858d489d'
down_revision: str | None = '33a3f2b716ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'currencyenum', ['INR', 'USD', 'USDC', 'ETH', 'BTC', 'CBBTC'],
                        [TableReference(table_schema='public', table_name='payment_transactions', column_name='currency')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'currencyenum', ['INR', 'USD', 'USDC', 'ETH', 'BTC'],
                        [TableReference(table_schema='public', table_name='payment_transactions', column_name='currency')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
