"""Create many-to-many prompt modifier-chat messages table

Revision ID: 73aabaf8775b
Revises: 1436fbf4f3b6
Create Date: 2024-11-22 01:05:26.871814+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73aabaf8775b'
down_revision: str | None = '1436fbf4f3b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('length', 'tone', 'style', 'formatting', 'complexity', 'other', name='modifiercategory').create(op.get_bind())
    op.create_table('prompt_modifiers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_modifier_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', postgresql.ENUM('length', 'tone', 'style', 'formatting', 'complexity', 'other', name='modifiercategory', create_type=False), server_default='other', nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('prompt_modifier_id', name=op.f('pk_prompt_modifiers'))
    )
    op.create_index(op.f('ix_prompt_modifiers_name'), 'prompt_modifiers', ['name'], unique=False)
    op.create_table('prompt_modifier_assocs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assoc_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_modifier_id', sa.Uuid(), nullable=False),
    sa.Column('chat_message_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.message_id'], name=op.f('fk_prompt_modifier_assocs_chat_message_id_chat_messages')),
    sa.ForeignKeyConstraint(['prompt_modifier_id'], ['prompt_modifiers.prompt_modifier_id'], name=op.f('fk_prompt_modifier_assocs_prompt_modifier_id_prompt_modifiers')),
    sa.PrimaryKeyConstraint('assoc_id', name=op.f('pk_prompt_modifier_assocs')),
    sa.UniqueConstraint('prompt_modifier_id', 'chat_message_id', name='uq_prompt_modifier_assoc')
    )
    op.create_index(op.f('ix_prompt_modifier_assocs_chat_message_id'), 'prompt_modifier_assocs', ['chat_message_id'], unique=False)
    op.create_index(op.f('ix_prompt_modifier_assocs_prompt_modifier_id'), 'prompt_modifier_assocs', ['prompt_modifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_modifier_assocs_prompt_modifier_id'), table_name='prompt_modifier_assocs')
    op.drop_index(op.f('ix_prompt_modifier_assocs_chat_message_id'), table_name='prompt_modifier_assocs')
    op.drop_table('prompt_modifier_assocs')
    op.drop_index(op.f('ix_prompt_modifiers_name'), table_name='prompt_modifiers')
    op.drop_table('prompt_modifiers')
    sa.Enum('length', 'tone', 'style', 'formatting', 'complexity', 'other', name='modifiercategory').drop(op.get_bind())
    # ### end Alembic commands ###
