"""Add index to turn_id on the turn quality table

Revision ID: 4a35af8edef7
Revises: 83c9625a31c2
Create Date: 2024-10-25 06:36:37.535161+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4a35af8edef7'
down_revision: str | None = '83c9625a31c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_turn_qualities_turn_id', 'turn_qualities', type_='unique')
    op.create_index(op.f('ix_turn_qualities_turn_id'), 'turn_qualities', ['turn_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_qualities_turn_id'), table_name='turn_qualities')
    op.create_unique_constraint('uq_turn_qualities_turn_id', 'turn_qualities', ['turn_id'])
    # ### end Alembic commands ###
