"""add model feedback reward action type

Revision ID: 0f7d4a848bf0
Revises: fb607f8371bd
Create Date: 2024-12-11 21:30:55.253852+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0f7d4a848bf0'
down_revision: str | None = 'fb607f8371bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'PROMPT', 'EVALUATION', 'QT_EVAL', 'TURN', 'FEEDBACK', 'MODEL_FEEDBACK'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'PROMPT', 'EVALUATION', 'QT_EVAL', 'TURN', 'FEEDBACK'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
