"""Add provider_settings column

Revision ID: 3e66d42698ff
Revises: 423417a77c49
Create Date: 2024-11-13 16:11:18.988858+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3e66d42698ff'
down_revision: str | None = '423417a77c49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('provider_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_models', 'provider_settings')
    # ### end Alembic commands ###
