"""add more facilitators to enumPaymentInstrumentFacilitatorEnum

Revision ID: 6fc1d7c7fa27
Revises: 4bbb19849516
Create Date: 2024-12-22 05:32:28.970318+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '6fc1d7c7fa27'
down_revision: str | None = '4bbb19849516'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN', 'BINANCE', 'CRYPTO_COM', 'UPI'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
