"""Add new columns to capture referred users' details

Revision ID: 72c94f92f387
Revises: 3aca3653b396
Create Date: 2024-12-30 06:18:16.694458+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72c94f92f387'
down_revision: str | None = '3aca3653b396'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlisted_users', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('waitlisted_users', sa.Column('google_provider_account_id', sa.Text(), nullable=True))
    op.add_column('waitlisted_users', sa.Column('google_account_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('waitlisted_users', sa.Column('user_image_url', sa.Text(), nullable=True))
    op.create_index(op.f('ix_waitlisted_users_google_provider_account_id'), 'waitlisted_users', ['google_provider_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlisted_users_google_provider_account_id'), table_name='waitlisted_users')
    op.drop_column('waitlisted_users', 'user_image_url')
    op.drop_column('waitlisted_users', 'google_account_tokens')
    op.drop_column('waitlisted_users', 'google_provider_account_id')
    op.drop_column('waitlisted_users', 'name')
    # ### end Alembic commands ###
