"""Add routing rule probability

Revision ID: 89cfd7919eff
Revises: 4c4101d68011
Create Date: 2024-12-02 11:01:24.015048+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '89cfd7919eff'
down_revision: str | None = '4c4101d68011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routing_rules', sa.Column('probability', sa.Numeric(precision=10, scale=6), server_default='1.0', nullable=True))
    op.alter_column('routing_rules', 'z_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routing_rules', 'z_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('routing_rules', 'probability')
    # ### end Alembic commands ###
