"""Update signup credits

Revision ID: 7e8e0e539bd8
Revises: 9b72acde8fb3
Create Date: 2024-12-05 12:07:55.260543+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7e8e0e539bd8'
down_revision: str | None = '9b72acde8fb3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'points', server_default="500")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'points', server_default="10000")
    # ### end Alembic commands ###
