"""adding a combined index for better read

Revision ID: 9b72acde8fb3
Revises: 38eb10ab835c
Create Date: 2024-12-05 11:59:30.475820+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9b72acde8fb3'
down_revision: str | None = '38eb10ab835c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reward_action_logs_user_turn', 'reward_action_logs', ['user_id', 'turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reward_action_logs_user_turn', table_name='reward_action_logs')
    # ### end Alembic commands ###
