"""added new enums to support plaid

Revision ID: 13f43eabf19c
Revises: 404e97438b5e
Create Date: 2024-12-28 10:35:50.418249+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '13f43eabf19c'
down_revision: str | None = '404e97438b5e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN', 'BINANCE', 'CRYPTO_COM', 'UPI', 'PLAID'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'paymentinstrumentidentifiertypeenum', ['UPI_ID', 'PHONE_NUMBER', 'EMAIL', 'CRYPTO_ADDRESS', 'BANK_ACCOUNT_NUMBER'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='identifier_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentidentifiertypeenum', 
                       ['UPI_ID', 'PHONE_NUMBER', 'EMAIL', 'CRYPTO_ADDRESS'],
                       [TableReference(table_schema='public', table_name='payment_instruments', column_name='identifier_type')],
                       enum_values_to_rename=[('BANK_ACCOUNT_NUMBER', 'UPI_ID')])
    
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', 
                       ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN', 'BINANCE', 'CRYPTO_COM', 'UPI'],
                       [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                       enum_values_to_rename=[('PLAID', 'BANK')])
    # ### end Alembic commands ###
