"""add streaming-metrics to cm

Revision ID: 534ef201f7f9
Revises: bded7608738c
Create Date: 2024-09-22 22:38:59.570121+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '534ef201f7f9'
down_revision: str | None = 'bded7608738c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('streaming_metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'streaming_metrics')
    # ### end Alembic commands ###
