"""make language_code nullable

Revision ID: 50c73502c70d
Revises: 1a7ed059dbe3
Create Date: 2024-10-08 17:38:29.845858+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50c73502c70d'
down_revision: str | None = '1a7ed059dbe3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'language_code',
               existing_type=postgresql.ENUM('AF', 'ALS', 'AM', 'AN', 'AR', 'ARZ', 'AS', 'AST', 'AV', 'AZ', 'AZB', 'BA', 'BAR', 'BCL', 'BE', 'BG', 'BH', 'BN', 'BO', 'BPY', 'BR', 'BS', 'BXR', 'CA', 'CBK', 'CE', 'CEB', 'CKB', 'CO', 'CS', 'CV', 'CY', 'DA', 'DE', 'DIQ', 'DSB', 'DTY', 'DV', 'EL', 'EML', 'EN', 'EO', 'ES', 'ET', 'EU', 'FA', 'FI', 'FR', 'FRR', 'FY', 'GA', 'GD', 'GL', 'GN', 'GOM', 'GU', 'GV', 'HE', 'HI', 'HIF', 'HR', 'HSB', 'HT', 'HU', 'HY', 'IA', 'ID', 'IE', 'ILO', 'IO', 'IS', 'IT', 'JA', 'JBO', 'JV', 'KA', 'KK', 'KM', 'KN', 'KO', 'KRC', 'KU', 'KV', 'KW', 'KY', 'LA', 'LB', 'LEZ', 'LI', 'LMO', 'LO', 'LRC', 'LT', 'LV', 'MAI', 'MG', 'MHR', 'MIN', 'MK', 'ML', 'MN', 'MR', 'MRJ', 'MS', 'MT', 'MWL', 'MY', 'MYV', 'MZN', 'NAH', 'NAP', 'NDS', 'NE', 'NEW', 'NL', 'NN', 'NO', 'OC', 'OR', 'OS', 'PA', 'PAM', 'PFL', 'PL', 'PMS', 'PNB', 'PS', 'PT', 'QU', 'RM', 'RO', 'RU', 'RUE', 'SA', 'SAH', 'SC', 'SCN', 'SCO', 'SD', 'SH', 'SI', 'SK', 'SL', 'SO', 'SQ', 'SR', 'SU', 'SV', 'SW', 'TA', 'TE', 'TG', 'TH', 'TK', 'TL', 'TR', 'TT', 'TYV', 'UG', 'UK', 'UR', 'UZ', 'VEC', 'VEP', 'VI', 'VLS', 'VO', 'WA', 'WAR', 'WUU', 'XAL', 'XMF', 'YI', 'YO', 'YUE', 'ZH', name='languagecode'),
               nullable=True,
               existing_server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'language_code',
               existing_type=postgresql.ENUM('AF', 'ALS', 'AM', 'AN', 'AR', 'ARZ', 'AS', 'AST', 'AV', 'AZ', 'AZB', 'BA', 'BAR', 'BCL', 'BE', 'BG', 'BH', 'BN', 'BO', 'BPY', 'BR', 'BS', 'BXR', 'CA', 'CBK', 'CE', 'CEB', 'CKB', 'CO', 'CS', 'CV', 'CY', 'DA', 'DE', 'DIQ', 'DSB', 'DTY', 'DV', 'EL', 'EML', 'EN', 'EO', 'ES', 'ET', 'EU', 'FA', 'FI', 'FR', 'FRR', 'FY', 'GA', 'GD', 'GL', 'GN', 'GOM', 'GU', 'GV', 'HE', 'HI', 'HIF', 'HR', 'HSB', 'HT', 'HU', 'HY', 'IA', 'ID', 'IE', 'ILO', 'IO', 'IS', 'IT', 'JA', 'JBO', 'JV', 'KA', 'KK', 'KM', 'KN', 'KO', 'KRC', 'KU', 'KV', 'KW', 'KY', 'LA', 'LB', 'LEZ', 'LI', 'LMO', 'LO', 'LRC', 'LT', 'LV', 'MAI', 'MG', 'MHR', 'MIN', 'MK', 'ML', 'MN', 'MR', 'MRJ', 'MS', 'MT', 'MWL', 'MY', 'MYV', 'MZN', 'NAH', 'NAP', 'NDS', 'NE', 'NEW', 'NL', 'NN', 'NO', 'OC', 'OR', 'OS', 'PA', 'PAM', 'PFL', 'PL', 'PMS', 'PNB', 'PS', 'PT', 'QU', 'RM', 'RO', 'RU', 'RUE', 'SA', 'SAH', 'SC', 'SCN', 'SCO', 'SD', 'SH', 'SI', 'SK', 'SL', 'SO', 'SQ', 'SR', 'SU', 'SV', 'SW', 'TA', 'TE', 'TG', 'TH', 'TK', 'TL', 'TR', 'TT', 'TYV', 'UG', 'UK', 'UR', 'UZ', 'VEC', 'VEP', 'VI', 'VLS', 'VO', 'WA', 'WAR', 'WUU', 'XAL', 'XMF', 'YI', 'YO', 'YUE', 'ZH', name='languagecode'),
               nullable=False,
               existing_server_default=sa.text("'EN'::languagecode"))
    # ### end Alembic commands ###
