"""added a payment transaction status of enum to indicate a reversed transaction for a failed transaction

Revision ID: fdcfb96df054
Revises: 6a92e359f4b6
Create Date: 2024-12-25 12:56:49.287815+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'fdcfb96df054'
down_revision: str | None = '6a92e359f4b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymenttransactionstatusenum', ['NOT_STARTED', 'PENDING', 'SUCCESS', 'FAILED', 'REVERSED'],
                        [TableReference(table_schema='public', table_name='payment_transactions', column_name='status', existing_server_default="'NOT_STARTED'::paymenttransactionstatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymenttransactionstatusenum', ['NOT_STARTED', 'PENDING', 'SUCCESS', 'FAILED'],
                        [TableReference(table_schema='public', table_name='payment_transactions', column_name='status', existing_server_default="'NOT_STARTED'::paymenttransactionstatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
