"""added a new points action enum for cashout reversals

Revision ID: 41d6d2179e76
Revises: fdcfb96df054
Create Date: 2024-12-25 13:10:36.818748+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '41d6d2179e76'
down_revision: str | None = 'fdcfb96df054'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'pointsactionenum', ['UNKNOWN', 'PROMPT', 'REWARD', 'CASHOUT', 'CASHOUT_REVERSED', 'ADJUSTMENT', 'EVALUATION', 'SIGN_UP'],
                        [TableReference(table_schema='public', table_name='point_transactions', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'pointsactionenum', ['UNKNOWN', 'PROMPT', 'REWARD', 'CASHOUT', 'ADJUSTMENT', 'EVALUATION', 'SIGN_UP'],
                        [TableReference(table_schema='public', table_name='point_transactions', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
