"""Add category relationship to ChatMessage

Revision ID: de6604182021
Revises: 238a41c46089
Create Date: 2024-09-09 18:34:34.704332+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'de6604182021'
down_revision: str | None = '238a41c46089'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('chat_messages_category_id_fkey'), 'chat_messages', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_messages_category_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'category_id')
    # ### end Alembic commands ###
