"""Add provider specific name

Revision ID: 2d36bae2f64f
Revises: b7d3de5fc21f
Create Date: 2024-09-29 01:44:59.112193+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2d36bae2f64f'
down_revision: str | None = 'b7d3de5fc21f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_model_provider_associations', sa.Column('provider_specific_model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_model_provider_associations', 'provider_specific_model_name')
    # ### end Alembic commands ###
