"""Add indices for faster feed sql read

Revision ID: 495367cf8ece
Revises: 3e66d42698ff
Create Date: 2024-11-15 12:35:34.611943+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '495367cf8ece'
down_revision: str | None = '3e66d42698ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_turn_id'), 'chat_messages', ['turn_id'], unique=False)
    op.create_index('ix_chats_created_at', 'chats', [sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_message_evals_eval_id'), 'message_evals', ['eval_id'], unique=False)
    op.create_index(op.f('ix_message_evals_message_id'), 'message_evals', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_evals_message_id'), table_name='message_evals')
    op.drop_index(op.f('ix_message_evals_eval_id'), table_name='message_evals')
    op.drop_index('ix_chats_created_at', table_name='chats')
    op.drop_index(op.f('ix_chat_messages_turn_id'), table_name='chat_messages')
    # ### end Alembic commands ###
