"""added creator_user_id to language_model table

Revision ID: 598040d1ab04
Revises: 1293a4867b20
Create Date: 2024-10-05 07:44:53.909455+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '598040d1ab04'
down_revision: str | None = '1293a4867b20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('creator_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(op.f('fk_language_models_creator_user_id_users'), 'language_models', 'users', ['creator_user_id'], ['user_id'])
    op.execute("""
    UPDATE language_models
    SET creator_user_id = 'SYSTEM'
    WHERE creator_user_id IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_language_models_creator_user_id_users'), 'language_models', type_='foreignkey')
    op.drop_column('language_models', 'creator_user_id')
    # ### end Alembic commands ###
