"""Add TURN enum

Revision ID: 5fdf565a327c
Revises: cafba08bd88f
Create Date: 2024-10-28 13:54:35.024489+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '5fdf565a327c'
down_revision: str | None = 'cafba08bd88f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'PROMPT', 'EVALUATION', 'TURN'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'PROMPT', 'EVALUATION'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
