"""Add strong model flag

Revision ID: 12258ea10905
Revises: 795f58a57af7
Create Date: 2024-12-03 09:16:12.530175+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '12258ea10905'
down_revision: str | None = '795f58a57af7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('is_strong', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_language_models_is_strong'), 'language_models', ['is_strong'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_models_is_strong'), table_name='language_models')
    op.drop_column('language_models', 'is_strong')
    # ### end Alembic commands ###
