"""Add turn_id to the Reward table

Revision ID: 83c9625a31c2
Revises: 6d0758afb565
Create Date: 2024-10-24 11:29:16.771323+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '83c9625a31c2'
down_revision: str | None = '6d0758afb565'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('turn_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_rewards_turn_id_turns'), 'rewards', 'turns', ['turn_id'], ['turn_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_rewards_turn_id_turns'), 'rewards', type_='foreignkey')
    op.drop_column('rewards', 'turn_id')
    # ### end Alembic commands ###
