"""add prompt moderation

Revision ID: 9acc8741e512
Revises: 14302794d558
Create Date: 2024-10-21 05:17:40.894343+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9acc8741e512'
down_revision: str | None = '14302794d558'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OTHER', 'VIOLENT_CRIMES', 'NON_VIOLENT_CRIMES', 'SEX_CRIMES', 'CHILD_EXPLOITATION', 'DEFAMATION', 'SPECIALIZED_ADVICE', 'PRIVACY', 'INTELLECTUAL_PROPERTY', 'INDISCERNATE_WEAPONS', 'HATE', 'SELF_HARM', 'SEXUAL_CONTENT', 'ELECTIONS', name='moderationreason').create(op.get_bind())
    op.add_column('turn_qualities', sa.Column('prompt_is_safe', sa.Boolean(), nullable=True))
    op.add_column('turn_qualities', sa.Column('prompt_moderation_model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('turn_qualities', sa.Column('prompt_unsafe_reasons', sa.ARRAY(postgresql.ENUM('OTHER', 'VIOLENT_CRIMES', 'NON_VIOLENT_CRIMES', 'SEX_CRIMES', 'CHILD_EXPLOITATION', 'DEFAMATION', 'SPECIALIZED_ADVICE', 'PRIVACY', 'INTELLECTUAL_PROPERTY', 'INDISCERNATE_WEAPONS', 'HATE', 'SELF_HARM', 'SEXUAL_CONTENT', 'ELECTIONS', name='moderationreason', create_type=False)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turn_qualities', 'prompt_unsafe_reasons')
    op.drop_column('turn_qualities', 'prompt_moderation_model_name')
    op.drop_column('turn_qualities', 'prompt_is_safe')
    sa.Enum('OTHER', 'VIOLENT_CRIMES', 'NON_VIOLENT_CRIMES', 'SEX_CRIMES', 'CHILD_EXPLOITATION', 'DEFAMATION', 'SPECIALIZED_ADVICE', 'PRIVACY', 'INTELLECTUAL_PROPERTY', 'INDISCERNATE_WEAPONS', 'HATE', 'SELF_HARM', 'SEXUAL_CONTENT', 'ELECTIONS', name='moderationreason').drop(op.get_bind())
    # ### end Alembic commands ###
