"""add attachments collection

Revision ID: f53563be6fc0
Revises: 72c94f92f387
Create Date: 2024-12-30 14:18:50.932434+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f53563be6fc0'
down_revision: str | None = '72c94f92f387'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.Column('chat_message_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.message_id'], name=op.f('fk_attachments_chat_message_id_chat_messages')),
    sa.PrimaryKeyConstraint('attachment_id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_chat_message_id'), 'attachments', ['chat_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_chat_message_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
