"""add high value reward ranges

Revision ID: 69aa6b992f76
Revises: 3146a88cdabb
Create Date: 2024-12-20 22:00:12.560441+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '69aa6b992f76'
down_revision: str | None = '3146a88cdabb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_amount_rules', sa.Column('high_min_value', sa.Integer(), nullable=True))
    op.add_column('reward_amount_rules', sa.Column('high_max_value', sa.Integer(), nullable=True))
    op.add_column('reward_amount_rules', sa.Column('high_mean_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reward_amount_rules', 'high_mean_value')
    op.drop_column('reward_amount_rules', 'high_max_value')
    op.drop_column('reward_amount_rules', 'high_min_value')
    # ### end Alembic commands ###
