"""Prepare to remove LMPA

Revision ID: 1a7ed059dbe3
Revises: 05974b81174a
Create Date: 2024-10-08 11:27:52.733731+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1a7ed059dbe3'
down_revision: str | None = '05974b81174a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('input_cost_usd_per_million_tokens', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('language_models', sa.Column('output_cost_usd_per_million_tokens', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('language_models', sa.Column('provider_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_language_models_provider_id_providers'), 'language_models', 'providers', ['provider_id'], ['provider_id'])
    # ### end Alembic commands ###
    op.execute(
        "UPDATE language_models lm SET input_cost_usd_per_million_tokens = lmpa.input_cost_usd_per_million_tokens FROM language_model_provider_associations lmpa WHERE lmpa.language_model_id = lm.language_model_id AND lmpa.input_cost_usd_per_million_tokens IS NOT NULL"
    )
    op.execute(
        "UPDATE language_models lm SET output_cost_usd_per_million_tokens = lmpa.output_cost_usd_per_million_tokens FROM language_model_provider_associations lmpa WHERE lmpa.language_model_id = lm.language_model_id AND lmpa.output_cost_usd_per_million_tokens IS NOT NULL"
    )


def downgrade() -> None:
    op.execute(
        "UPDATE language_model_provider_associations lmpa SET input_cost_usd_per_million_tokens = lm.input_cost_usd_per_million_tokens FROM language_models lm WHERE lmpa.language_model_id = lm.language_model_id AND lm.input_cost_usd_per_million_tokens IS NOT NULL"
    )
    op.execute(
        "UPDATE language_model_provider_associations lmpa SET output_cost_usd_per_million_tokens = lm.output_cost_usd_per_million_tokens FROM language_models lm WHERE lmpa.language_model_id = lm.language_model_id AND lm.output_cost_usd_per_million_tokens IS NOT NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_language_models_provider_id_providers'), 'language_models', type_='foreignkey')
    op.drop_column('language_models', 'provider_id')
    op.drop_column('language_models', 'output_cost_usd_per_million_tokens')
    op.drop_column('language_models', 'input_cost_usd_per_million_tokens')
    # ### end Alembic commands ###
