"""add language code enum to chat messages

Revision ID: e57e32b5aed7
Revises: c28f406d85cd
Create Date: 2024-09-19 17:12:47.716510+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e57e32b5aed7'
down_revision: str | None = 'c28f406d85cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('AF', 'AR', 'BG', 'BN', 'CA', 'CS', 'CY', 'DA', 'DE', 'EL', 'EN', 'ES', 'ET', 'FA', 'FI', 'FR', 'GU', 'HE', 'HI', 'HR', 'HU', 'ID', 'IT', 'JA', 'KN', 'KO', 'LT', 'LV', 'MK', 'ML', 'MR', 'NE', 'NL', 'NO', 'PA', 'PL', 'PT', 'RO', 'RU', 'SK', 'SL', 'SO', 'SQ', 'SV', 'SW', 'TA', 'TE', 'TH', 'TL', 'TR', 'UK', 'UR', 'VI', 'ZH_CN', 'ZH_TW', name='languagecode').create(op.get_bind())
    op.add_column('chat_messages', sa.Column('language_code', postgresql.ENUM('AF', 'AR', 'BG', 'BN', 'CA', 'CS', 'CY', 'DA', 'DE', 'EL', 'EN', 'ES', 'ET', 'FA', 'FI', 'FR', 'GU', 'HE', 'HI', 'HR', 'HU', 'ID', 'IT', 'JA', 'KN', 'KO', 'LT', 'LV', 'MK', 'ML', 'MR', 'NE', 'NL', 'NO', 'PA', 'PL', 'PT', 'RO', 'RU', 'SK', 'SL', 'SO', 'SQ', 'SV', 'SW', 'TA', 'TE', 'TH', 'TL', 'TR', 'UK', 'UR', 'VI', 'ZH_CN', 'ZH_TW', name='languagecode', create_type=False), nullable=True))
    op.execute("UPDATE chat_messages SET language_code = 'EN' WHERE language_code IS NULL")
    op.alter_column('chat_messages', 'language_code', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'language_code')
    sa.Enum('AF', 'AR', 'BG', 'BN', 'CA', 'CS', 'CY', 'DA', 'DE', 'EL', 'EN', 'ES', 'ET', 'FA', 'FI', 'FR', 'GU', 'HE', 'HI', 'HR', 'HU', 'ID', 'IT', 'JA', 'KN', 'KO', 'LT', 'LV', 'MK', 'ML', 'MR', 'NE', 'NL', 'NO', 'PA', 'PL', 'PT', 'RO', 'RU', 'SK', 'SL', 'SO', 'SQ', 'SV', 'SW', 'TA', 'TE', 'TH', 'TL', 'TR', 'UK', 'UR', 'VI', 'ZH_CN', 'ZH_TW', name='languagecode').drop(op.get_bind())
    # ### end Alembic commands ###
