"""add snapshot time, wins, losses to ratings history

Revision ID: b35fa39d0be1
Revises: 349401e65d76
Create Date: 2024-08-28 03:22:03.473520+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b35fa39d0be1'
down_revision: str | None = '349401e65d76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings_history', sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False))
    op.add_column('ratings_history', sa.Column('wins', sa.Integer(), nullable=False))
    op.add_column('ratings_history', sa.Column('losses', sa.Integer(), nullable=False))
    op.add_column('ratings_history', sa.Column('ties', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings_history', 'ties')
    op.drop_column('ratings_history', 'losses')
    op.drop_column('ratings_history', 'wins')
    op.drop_column('ratings_history', 'snapshot_timestamp')
    # ### end Alembic commands ###
