"""Add index to provider_id foreign key on the language models table

Revision ID: 3dc4fad174d4
Revises: bb67ead65b47
Create Date: 2024-10-25 20:05:26.041409+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3dc4fad174d4'
down_revision: str | None = 'bb67ead65b47'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_language_models_internal_name'), 'language_models', ['internal_name'], unique=False)
    op.create_index(op.f('ix_language_models_provider_id'), 'language_models', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_models_provider_id'), table_name='language_models')
    op.drop_index(op.f('ix_language_models_internal_name'), table_name='language_models')
    # ### end Alembic commands ###
