"""Add assistant_language_model_id to chat messages

Revision ID: c6e61ed3c778
Revises: 2d36bae2f64f
Create Date: 2024-09-29 02:02:56.795830+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c6e61ed3c778'
down_revision: str | None = '2d36bae2f64f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('assistant_language_model_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_chat_messages_assistant_language_model_id_language_models'), 'chat_messages', 'language_models', ['assistant_language_model_id'], ['language_model_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chat_messages_assistant_language_model_id_language_models'), 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'assistant_language_model_id')
    # ### end Alembic commands ###
