"""add prompt difficulty details

Revision ID: fb607f8371bd
Revises: e17eacee25db
Create Date: 2024-12-10 20:38:59.620648+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fb607f8371bd'
down_revision: str | None = 'e17eacee25db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turn_qualities', sa.Column('prompt_difficulty_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turn_qualities', 'prompt_difficulty_details')
    # ### end Alembic commands ###
