"""add inference_succeeded

Revision ID: 4bbb19849516
Revises: 69aa6b992f76
Create Date: 2024-12-21 04:03:02.159021+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '4bbb19849516'
down_revision: str | None = '69aa6b992f76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'languagemodelresponsestatusenum', ['OK', 'SLOW_RESPONSE', 'TIMEOUT', 'CONNECTION_REFUSED', 'STREAMING_INTERRUPTED', 'INFERENCE_FAILED', 'INFERENCE_SUCCEEDED', 'OTHER'],
                        [TableReference(table_schema='public', table_name='language_model_response_statuses', column_name='status_type', existing_server_default="'OTHER'::languagemodelresponsestatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'languagemodelresponsestatusenum', ['OK', 'SLOW_RESPONSE', 'TIMEOUT', 'CONNECTION_REFUSED', 'STREAMING_INTERRUPTED', 'INFERENCE_FAILED', 'OTHER'],
                        [TableReference(table_schema='public', table_name='language_model_response_statuses', column_name='status_type', existing_server_default="'OTHER'::languagemodelresponsestatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
