"""add ui state columns to chat_message

Revision ID: 7df7107cf593
Revises: 4bd4eaab8682
Create Date: 2024-10-01 02:01:05.875776+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7df7107cf593'
down_revision: str | None = '4bd4eaab8682'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('UNKNOWN', 'SEEN', 'DISMISSED', 'SELECTED', name='messageuistatus').create(op.get_bind())
    op.add_column('chat_messages', sa.Column('ui_status', postgresql.ENUM('UNKNOWN', 'SEEN', 'DISMISSED', 'SELECTED', name='messageuistatus', create_type=False), server_default='UNKNOWN', nullable=False))
    op.add_column('chat_messages', sa.Column('turn_sequence_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'turn_sequence_number')
    op.drop_column('chat_messages', 'ui_status')
    sa.Enum('UNKNOWN', 'SEEN', 'DISMISSED', 'SELECTED', name='messageuistatus').drop(op.get_bind())
    # ### end Alembic commands ###
