"""Add LM statistics columns to LLMs table

Revision ID: 1cc1f1a9a081
Revises: 9acc8741e512
Create Date: 2024-10-22 05:42:35.332447+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1cc1f1a9a081'
down_revision: str | None = '9acc8741e512'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('first_token_avg_latency_ms', sa.Float(), nullable=True))
    op.add_column('language_models', sa.Column('first_token_p90_latency_ms', sa.Float(), nullable=True))
    op.add_column('language_models', sa.Column('output_avg_tps', sa.Float(), nullable=True))
    op.add_column('language_models', sa.Column('output_p90_tps', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_models', 'output_p90_tps')
    op.drop_column('language_models', 'output_avg_tps')
    op.drop_column('language_models', 'first_token_p90_latency_ms')
    op.drop_column('language_models', 'first_token_avg_latency_ms')
    # ### end Alembic commands ###
