"""add reward rule action type

Revision ID: ec62f1aeb675
Revises: f24c498fd8c6
Create Date: 2024-12-13 02:29:14.247197+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec62f1aeb675'
down_revision: str | None = 'f24c498fd8c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_amount_rules', sa.Column('action_type', postgresql.ENUM('SIGN_UP', 'PROMPT', 'EVALUATION', 'QT_EVAL', 'TURN', 'FEEDBACK', 'MODEL_FEEDBACK', name='rewardactionenum', create_type=False), nullable=False, server_default='TURN'))
    op.add_column('reward_probability_rules', sa.Column('action_type', postgresql.ENUM('SIGN_UP', 'PROMPT', 'EVALUATION', 'QT_EVAL', 'TURN', 'FEEDBACK', 'MODEL_FEEDBACK', name='rewardactionenum', create_type=False), nullable=False, server_default='TURN'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reward_probability_rules', 'action_type')
    op.drop_column('reward_amount_rules', 'action_type')
    # ### end Alembic commands ###
