"""Add Language Models table.

Revision ID: ea6676883cd1
Revises: c038d6705e19
Create Date: 2024-08-21 20:48:33.453796+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea6676883cd1'
down_revision: str | None = 'c038d6705e19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('unknown', 'apache_2_0', 'mit', 'openrail', 'bigscience_openrail_m', 'creativeml_openrail_m', 'bigscience_bloom_rail_1_0', 'bigcode_openrail_m', 'afl_3_0', 'artistic_2_0', 'bsl_1_0', 'bsd', 'bsd_2_clause', 'bsd_3_clause', 'bsd_3_clause_clear', 'c_uda', 'cc', 'cc0_1_0', 'cc_by_2_0', 'cc_by_2_5', 'cc_by_3_0', 'cc_by_4_0', 'cc_by_sa_3_0', 'cc_by_sa_4_0', 'cc_by_nc_2_0', 'cc_by_nc_3_0', 'cc_by_nc_4_0', 'cc_by_nd_4_0', 'cc_by_nc_nd_3_0', 'cc_by_nc_nd_4_0', 'cc_by_nc_sa_2_0', 'cc_by_nc_sa_3_0', 'cc_by_nc_sa_4_0', 'cdla_sharing_1_0', 'cdla_permissive_1_0', 'cdla_permissive_2_0', 'wtfpl', 'ecl_2_0', 'epl_1_0', 'epl_2_0', 'etalab_2_0', 'eupl_1_1', 'agpl_3_0', 'gfdl', 'gpl', 'gpl_2_0', 'gpl_3_0', 'lgpl', 'lgpl_2_1', 'lgpl_3_0', 'isc', 'lppl_1_3c', 'ms_pl', 'apple_ascl', 'mpl_2_0', 'odc_by', 'odbl', 'openrail_pp', 'osl_3_0', 'postgresql', 'ofl_1_1', 'ncsa', 'unlicense', 'zlib', 'pddl', 'lgpl_lr', 'deepfloyd_if_license', 'llama2', 'llama3', 'gemma', 'other', name='licenseenum').create(op.get_bind())
    op.create_table('language_models',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('internal_name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('license', postgresql.ENUM('unknown', 'apache_2_0', 'mit', 'openrail', 'bigscience_openrail_m', 'creativeml_openrail_m', 'bigscience_bloom_rail_1_0', 'bigcode_openrail_m', 'afl_3_0', 'artistic_2_0', 'bsl_1_0', 'bsd', 'bsd_2_clause', 'bsd_3_clause', 'bsd_3_clause_clear', 'c_uda', 'cc', 'cc0_1_0', 'cc_by_2_0', 'cc_by_2_5', 'cc_by_3_0', 'cc_by_4_0', 'cc_by_sa_3_0', 'cc_by_sa_4_0', 'cc_by_nc_2_0', 'cc_by_nc_3_0', 'cc_by_nc_4_0', 'cc_by_nd_4_0', 'cc_by_nc_nd_3_0', 'cc_by_nc_nd_4_0', 'cc_by_nc_sa_2_0', 'cc_by_nc_sa_3_0', 'cc_by_nc_sa_4_0', 'cdla_sharing_1_0', 'cdla_permissive_1_0', 'cdla_permissive_2_0', 'wtfpl', 'ecl_2_0', 'epl_1_0', 'epl_2_0', 'etalab_2_0', 'eupl_1_1', 'agpl_3_0', 'gfdl', 'gpl', 'gpl_2_0', 'gpl_3_0', 'lgpl', 'lgpl_2_1', 'lgpl_3_0', 'isc', 'lppl_1_3c', 'ms_pl', 'apple_ascl', 'mpl_2_0', 'odc_by', 'odbl', 'openrail_pp', 'osl_3_0', 'postgresql', 'ofl_1_1', 'ncsa', 'unlicense', 'zlib', 'pddl', 'lgpl_lr', 'deepfloyd_if_license', 'llama2', 'llama3', 'gemma', 'other', name='licenseenum', create_type=False), nullable=False),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('model_id', name=op.f('language_models_pkey')),
    sa.UniqueConstraint('internal_name', name=op.f('language_models_internal_name_key'))
    )
    op.create_index(op.f('ix_language_models_name'), 'language_models', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_models_name'), table_name='language_models')
    op.drop_table('language_models')
    sa.Enum('unknown', 'apache_2_0', 'mit', 'openrail', 'bigscience_openrail_m', 'creativeml_openrail_m', 'bigscience_bloom_rail_1_0', 'bigcode_openrail_m', 'afl_3_0', 'artistic_2_0', 'bsl_1_0', 'bsd', 'bsd_2_clause', 'bsd_3_clause', 'bsd_3_clause_clear', 'c_uda', 'cc', 'cc0_1_0', 'cc_by_2_0', 'cc_by_2_5', 'cc_by_3_0', 'cc_by_4_0', 'cc_by_sa_3_0', 'cc_by_sa_4_0', 'cc_by_nc_2_0', 'cc_by_nc_3_0', 'cc_by_nc_4_0', 'cc_by_nd_4_0', 'cc_by_nc_nd_3_0', 'cc_by_nc_nd_4_0', 'cc_by_nc_sa_2_0', 'cc_by_nc_sa_3_0', 'cc_by_nc_sa_4_0', 'cdla_sharing_1_0', 'cdla_permissive_1_0', 'cdla_permissive_2_0', 'wtfpl', 'ecl_2_0', 'epl_1_0', 'epl_2_0', 'etalab_2_0', 'eupl_1_1', 'agpl_3_0', 'gfdl', 'gpl', 'gpl_2_0', 'gpl_3_0', 'lgpl', 'lgpl_2_1', 'lgpl_3_0', 'isc', 'lppl_1_3c', 'ms_pl', 'apple_ascl', 'mpl_2_0', 'odc_by', 'odbl', 'openrail_pp', 'osl_3_0', 'postgresql', 'ofl_1_1', 'ncsa', 'unlicense', 'zlib', 'pddl', 'lgpl_lr', 'deepfloyd_if_license', 'llama2', 'llama3', 'gemma', 'other', name='licenseenum').drop(op.get_bind())
    # ### end Alembic commands ###
