"""add adjustment transaction type

Revision ID: a5494c7bc59c
Revises: 1d82f52ceb93
Create Date: 2024-12-16 06:34:56.291621+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'a5494c7bc59c'
down_revision: str | None = '1d82f52ceb93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'pointsactionenum', ['UNKNOWN', 'SIGN_UP', 'REWARD', 'CASHOUT', 'ADJUSTMENT', 'PROMPT', 'EVALUATION'],
                        [TableReference(table_schema='public', table_name='point_transactions', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'pointsactionenum', ['UNKNOWN', 'SIGN_UP', 'REWARD', 'CASHOUT', 'PROMPT', 'EVALUATION'],
                        [TableReference(table_schema='public', table_name='point_transactions', column_name='action_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
