"""updated scale of the new columns

Revision ID: c28f406d85cd
Revises: 95e47bd0fdb4
Create Date: 2024-09-12 08:54:32.262994+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c28f406d85cd'
down_revision: str | None = '95e47bd0fdb4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_model_provider_associations', 'input_cost_usd_per_million_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('language_model_provider_associations', 'output_cost_usd_per_million_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_model_provider_associations', 'output_cost_usd_per_million_tokens',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('language_model_provider_associations', 'input_cost_usd_per_million_tokens',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
