"""Add model error rate table

Revision ID: 795f58a57af7
Revises: 89cfd7919eff
Create Date: 2024-12-03 04:10:07.193344+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '795f58a57af7'
down_revision: str | None = '89cfd7919eff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OK', 'SLOW_RESPONSE', 'TIMEOUT', 'CONNECTION_REFUSED', 'STREAMING_INTERRUPTED', 'OTHER', name='languagemodelresponsestatusenum').create(op.get_bind())
    op.create_table('language_model_response_statuses',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language_model_response_status_id', sa.Uuid(), nullable=False),
    sa.Column('language_model_id', sa.Uuid(), nullable=False),
    sa.Column('http_response_code', sa.Integer(), nullable=True),
    sa.Column('status_type', postgresql.ENUM('OK', 'SLOW_RESPONSE', 'TIMEOUT', 'CONNECTION_REFUSED', 'STREAMING_INTERRUPTED', 'OTHER', name='languagemodelresponsestatusenum', create_type=False), server_default='OTHER', nullable=False),
    sa.Column('status_message', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['language_model_id'], ['language_models.language_model_id'], name=op.f('fk_language_model_response_statuses_language_model_id_language_models')),
    sa.PrimaryKeyConstraint('language_model_response_status_id', name=op.f('pk_language_model_response_statuses'))
    )
    op.create_index(op.f('ix_language_model_response_statuses_status_type'), 'language_model_response_statuses', ['status_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_model_response_statuses_status_type'), table_name='language_model_response_statuses')
    op.drop_table('language_model_response_statuses')
    sa.Enum('OK', 'SLOW_RESPONSE', 'TIMEOUT', 'CONNECTION_REFUSED', 'STREAMING_INTERRUPTED', 'OTHER', name='languagemodelresponsestatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
