"""added status column to language_models

Revision ID: d800258eaf87
Revises: 6c3ca630eec7
Create Date: 2024-10-04 09:43:21.658824+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd800258eaf87'
down_revision: str | None = '6c3ca630eec7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SUBMITTED', 'VERIFIED_PENDING_ACTIVATION', 'REJECTED', 'ACTIVE', 'INACTIVE', name='languagemodelstatusenum').create(op.get_bind())
    op.add_column('language_models', sa.Column('status', postgresql.ENUM('SUBMITTED', 'VERIFIED_PENDING_ACTIVATION', 'REJECTED', 'ACTIVE', 'INACTIVE', name='languagemodelstatusenum', create_type=False), server_default='SUBMITTED', nullable=True))
    op.alter_column('language_models', 'license',
               existing_type=postgresql.ENUM('unknown', 'apache_2_0', 'mit', 'openrail', 'bigscience_openrail_m', 'creativeml_openrail_m', 'bigscience_bloom_rail_1_0', 'bigcode_openrail_m', 'afl_3_0', 'artistic_2_0', 'bsl_1_0', 'bsd', 'bsd_2_clause', 'bsd_3_clause', 'bsd_3_clause_clear', 'c_uda', 'cc', 'cc0_1_0', 'cc_by_2_0', 'cc_by_2_5', 'cc_by_3_0', 'cc_by_4_0', 'cc_by_sa_3_0', 'cc_by_sa_4_0', 'cc_by_nc_2_0', 'cc_by_nc_3_0', 'cc_by_nc_4_0', 'cc_by_nd_4_0', 'cc_by_nc_nd_3_0', 'cc_by_nc_nd_4_0', 'cc_by_nc_sa_2_0', 'cc_by_nc_sa_3_0', 'cc_by_nc_sa_4_0', 'cdla_sharing_1_0', 'cdla_permissive_1_0', 'cdla_permissive_2_0', 'wtfpl', 'ecl_2_0', 'epl_1_0', 'epl_2_0', 'etalab_2_0', 'eupl_1_1', 'agpl_3_0', 'gfdl', 'gpl', 'gpl_2_0', 'gpl_3_0', 'lgpl', 'lgpl_2_1', 'lgpl_3_0', 'isc', 'lppl_1_3c', 'ms_pl', 'apple_ascl', 'mpl_2_0', 'odc_by', 'odbl', 'openrail_pp', 'osl_3_0', 'postgresql', 'ofl_1_1', 'ncsa', 'unlicense', 'zlib', 'pddl', 'lgpl_lr', 'deepfloyd_if_license', 'llama2', 'llama3', 'gemma', 'other', name='licenseenum'),
               nullable=True,
               server_default='unknown')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_models', 'license',
               existing_type=postgresql.ENUM('unknown', 'apache_2_0', 'mit', 'openrail', 'bigscience_openrail_m', 'creativeml_openrail_m', 'bigscience_bloom_rail_1_0', 'bigcode_openrail_m', 'afl_3_0', 'artistic_2_0', 'bsl_1_0', 'bsd', 'bsd_2_clause', 'bsd_3_clause', 'bsd_3_clause_clear', 'c_uda', 'cc', 'cc0_1_0', 'cc_by_2_0', 'cc_by_2_5', 'cc_by_3_0', 'cc_by_4_0', 'cc_by_sa_3_0', 'cc_by_sa_4_0', 'cc_by_nc_2_0', 'cc_by_nc_3_0', 'cc_by_nc_4_0', 'cc_by_nd_4_0', 'cc_by_nc_nd_3_0', 'cc_by_nc_nd_4_0', 'cc_by_nc_sa_2_0', 'cc_by_nc_sa_3_0', 'cc_by_nc_sa_4_0', 'cdla_sharing_1_0', 'cdla_permissive_1_0', 'cdla_permissive_2_0', 'wtfpl', 'ecl_2_0', 'epl_1_0', 'epl_2_0', 'etalab_2_0', 'eupl_1_1', 'agpl_3_0', 'gfdl', 'gpl', 'gpl_2_0', 'gpl_3_0', 'lgpl', 'lgpl_2_1', 'lgpl_3_0', 'isc', 'lppl_1_3c', 'ms_pl', 'apple_ascl', 'mpl_2_0', 'odc_by', 'odbl', 'openrail_pp', 'osl_3_0', 'postgresql', 'ofl_1_1', 'ncsa', 'unlicense', 'zlib', 'pddl', 'lgpl_lr', 'deepfloyd_if_license', 'llama2', 'llama3', 'gemma', 'other', name='licenseenum'),
               nullable=False)
    op.drop_column('language_models', 'status')
    sa.Enum('SUBMITTED', 'VERIFIED_PENDING_ACTIVATION', 'REJECTED', 'ACTIVE', 'INACTIVE', name='languagemodelstatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
