"""add paypal id and venmo id to type of instrument identifier similar to upi id

Revision ID: 329e464ccf03
Revises: a71abdbe3b89
Create Date: 2025-02-07 17:51:21.663631+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '329e464ccf03'
down_revision: str | None = 'a71abdbe3b89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentidentifiertypeenum', ['UPI_ID', 'PHONE_NUMBER', 'EMAIL', 'CRYPTO_ADDRESS', 'BANK_ACCOUNT_NUMBER', 'PARTNER_IDENTIFIER', 'PAYPAL_ID', 'VENMO_ID'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='identifier_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentidentifiertypeenum', ['UPI_ID', 'PHONE_NUMBER', 'EMAIL', 'CRYPTO_ADDRESS', 'BANK_ACCOUNT_NUMBER', 'PARTNER_IDENTIFIER'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='identifier_type')],
                        enum_values_to_rename=[('PAYPAL_ID', 'PARTNER_IDENTIFIER'), ('VENMO_ID', 'PARTNER_IDENTIFIER')])
    # ### end Alembic commands ###
