"""routing info table

Revision ID: 3083d3c6cab5
Revises: 9baeb50def99
Create Date: 2025-03-11 00:18:00.983778+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3083d3c6cab5'
down_revision: str | None = '9baeb50def99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_info',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('routing_info_id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('selector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('routing_outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], name=op.f('fk_routing_info_turn_id_turns')),
    sa.PrimaryKeyConstraint('routing_info_id', name=op.f('pk_routing_info'))
    )
    op.create_index(op.f('ix_routing_info_turn_id'), 'routing_info', ['turn_id'], unique=False)
    op.add_column('chat_messages', sa.Column('routing_info_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_chat_messages_routing_info_id_routing_info'), 'chat_messages', 'routing_info', ['routing_info_id'], ['routing_info_id'])
    op.drop_column('turns', 'required_models_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('required_models_types', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_chat_messages_routing_info_id_routing_info'), 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'routing_info_id')
    op.drop_index(op.f('ix_routing_info_turn_id'), table_name='routing_info')
    op.drop_table('routing_info')
    # ### end Alembic commands ###
