"""adding new enums for ChatCompletion

Revision ID: 878219f0bca2
Revises: 41fce37570e0
Create Date: 2025-01-24 05:31:20.600434+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '878219f0bca2'
down_revision: str | None = '41fce37570e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'completionstatus', ['SUCCESS', 'USER_ABORTED', 'PROVIDER_ERROR', 'STREAMING_ERROR', 'STREAMING_ERROR_WITH_FALLBACK', 'SYSTEM_ERROR'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='completion_status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'completionstatus', ['SUCCESS', 'USER_ABORTED', 'PROVIDER_ERROR', 'SYSTEM_ERROR'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='completion_status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
