"""Add unsubscribed_from_marketing column on Users table

Revision ID: d32c9d7a3041
Revises: 2b7cfcb0ff81
Create Date: 2025-02-04 22:57:24.529967+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd32c9d7a3041'
down_revision: str | None = '2b7cfcb0ff81'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unsubscribed_from_marketing', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unsubscribed_from_marketing')
    # ### end Alembic commands ###
