"""add turn id to app feedback

Revision ID: bd29a465320f
Revises: 24eeb87036eb
Create Date: 2025-02-03 21:07:33.299394+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'bd29a465320f'
down_revision: str | None = '24eeb87036eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_feedback', sa.Column('turn_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_app_feedback_turn_id'), 'app_feedback', ['turn_id'], unique=False)
    op.create_foreign_key(op.f('fk_app_feedback_turn_id_turns'), 'app_feedback', 'turns', ['turn_id'], ['turn_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_app_feedback_turn_id_turns'), 'app_feedback', type_='foreignkey')
    op.drop_index(op.f('ix_app_feedback_turn_id'), table_name='app_feedback')
    op.drop_column('app_feedback', 'turn_id')
    # ### end Alembic commands ###
