"""created a table to keep track of daily account balances

Revision ID: 24eeb87036eb
Revises: a67988201284
Create Date: 2025-02-03 11:36:20.354794+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24eeb87036eb'
down_revision: str | None = 'a67988201284'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_account_balance_history',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_account_balance_id', sa.Uuid(), nullable=False),
    sa.Column('payment_instrument_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', postgresql.ENUM('INR', 'USD', 'USDC', 'ETH', 'BTC', 'CBBTC', name='currencyenum', create_type=False), nullable=False),
    sa.Column('balance', sa.Numeric(precision=30, scale=18), nullable=False),
    sa.ForeignKeyConstraint(['payment_instrument_id'], ['payment_instruments.payment_instrument_id'], name=op.f('fk_daily_account_balance_history_payment_instrument_id_payment_instruments')),
    sa.PrimaryKeyConstraint('daily_account_balance_id', name=op.f('pk_daily_account_balance_history'))
    )
    op.create_index(op.f('ix_daily_account_balance_history_payment_instrument_id'), 'daily_account_balance_history', ['payment_instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_account_balance_history_payment_instrument_id'), table_name='daily_account_balance_history')
    op.drop_table('daily_account_balance_history')
    # ### end Alembic commands ###
