"""add waitlist type

Revision ID: 3dc92077600f
Revises: cea1251ef2db
Create Date: 2025-01-06 23:06:06.706748+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dc92077600f'
down_revision: str | None = 'cea1251ef2db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NO_INVITE_CODE', 'SIGN_IN_METHOD_NOT_AVAILABLE', name='waitlisttype').create(op.get_bind())
    op.add_column('waitlisted_users', sa.Column('waitlist_type', postgresql.ENUM('NO_INVITE_CODE', 'SIGN_IN_METHOD_NOT_AVAILABLE', name='waitlisttype', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlisted_users', 'waitlist_type')
    sa.Enum('NO_INVITE_CODE', 'SIGN_IN_METHOD_NOT_AVAILABLE', name='waitlisttype').drop(op.get_bind())
    # ### end Alembic commands ###
