"""add cross check review

Revision ID: 2fb5a430edba
Revises: a80425a6f686
Create Date: 2025-03-06 01:54:35.726584+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '2fb5a430edba'
down_revision: str | None = 'a80425a6f686'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'reviewtype', ['BINARY', 'CRITIQUE', 'SEGMENTED', 'NUGGETIZED', 'CROSS_CHECK'],
                        [TableReference(table_schema='public', table_name='message_reviews', column_name='review_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'reviewtype', ['BINARY', 'CRITIQUE', 'SEGMENTED', 'NUGGETIZED'],
                        [TableReference(table_schema='public', table_name='message_reviews', column_name='review_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
