"""add promotions status field

Revision ID: c4832b474db6
Revises: b540f1efb7cf
Create Date: 2025-02-04 06:55:42.698337+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4832b474db6'
down_revision: str | None = 'b540f1efb7cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'INACTIVE', name='modelpromotionstatus').create(op.get_bind())
    op.add_column('model_promotions', sa.Column('promo_status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='modelpromotionstatus', create_type=False), nullable=False))
    op.drop_column('model_promotions', 'in_promo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_promotions', sa.Column('in_promo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('model_promotions', 'promo_status')
    sa.Enum('ACTIVE', 'INACTIVE', name='modelpromotionstatus').drop(op.get_bind())
    # ### end Alembic commands ###
