"""add column for model information, likely hugging face

Revision ID: 85aad109fb5e
Revises: 79b2bd75a908
Create Date: 2025-01-09 22:27:55.457834+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '85aad109fb5e'
down_revision: str | None = '79b2bd75a908'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('external_model_info_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_models', 'external_model_info_url')
    # ### end Alembic commands ###
