"""create checkout_com entry

Revision ID: 88c3904cd8e0
Revises: 1720fe8a27a0
Create Date: 2025-01-29 13:19:25.650457+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from dotenv import load_dotenv

from ypl.db.oneoffs.create_checkoutcom_payment_instrument import add_checkoutcom_source_payment_instrument, remove_checkoutcom_source_payment_instrument


# revision identifiers, used by Alembic.
revision: str = '88c3904cd8e0'
down_revision: str | None = '1720fe8a27a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    add_checkoutcom_source_payment_instrument(connection)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    remove_checkoutcom_source_payment_instrument(connection)
    pass
    # ### end Alembic commands ###
