"""Add modality enum to prompt modifier, defaults to text

Revision ID: 1a6ebbca7830
Revises: 4bf3d475e901
Create Date: 2025-03-10 18:39:27.778537+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a6ebbca7830'
down_revision: str | None = '4bf3d475e901'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('TEXT', 'IMAGE', name='modifiermodality').create(op.get_bind())
    op.add_column('prompt_modifiers', sa.Column('modality', postgresql.ENUM('TEXT', 'IMAGE', name='modifiermodality', create_type=False), server_default='TEXT', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_modifiers', 'modality')
    sa.Enum('TEXT', 'IMAGE', name='modifiermodality').drop(op.get_bind())
    # ### end Alembic commands ###
