"""add lm taxonomy

Revision ID: e49037cc0a53
Revises: 558685d40d27
Create Date: 2025-02-14 00:51:47.403277+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e49037cc0a53'
down_revision: str | None = '558685d40d27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('model_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('language_models', sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('language_models', sa.Column('model_release', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_models', 'model_release')
    op.drop_column('language_models', 'model_version')
    op.drop_column('language_models', 'model_class')
    # ### end Alembic commands ###
