"""create source account for paypal

Revision ID: cc84d8417cef
Revises: 417e7bbc0848
Create Date: 2025-02-12 13:31:46.343469+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from dotenv import load_dotenv

from ypl.db.oneoffs.create_paypal_payment_instrument import (
    add_paypal_source_payment_instrument,
    remove_paypal_source_payment_instrument,
)


# revision identifiers, used by Alembic.
revision: str = 'cc84d8417cef'
down_revision: str | None = '417e7bbc0848'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    add_paypal_source_payment_instrument(connection)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    remove_paypal_source_payment_instrument(connection)
    # ### end Alembic commands ###
