"""taxonomy rank

Revision ID: 45eb01d4c4cf
Revises: f506d37928ad
Create Date: 2025-02-26 21:49:18.470538+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45eb01d4c4cf'
down_revision: str | None = 'f506d37928ad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_model_taxonomy', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_model_taxonomy', 'priority')
    # ### end Alembic commands ###
