"""add a USD amount column to payment_transactions table

Revision ID: a71abdbe3b89
Revises: ead5e4a5a98f
Create Date: 2025-02-07 06:02:32.094671+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a71abdbe3b89'
down_revision: str | None = 'ead5e4a5a98f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('usd_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'usd_amount')
    # ### end Alembic commands ###
