"""new completion status for first token timeout

Revision ID: 0cb833c08b38
Revises: 2e9f39b7ce9e
Create Date: 2025-03-03 04:37:07.552912+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0cb833c08b38'
down_revision: str | None = '2e9f39b7ce9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'completionstatus', ['SUCCESS', 'USER_ABORTED', 'PROVIDER_ERROR', 'STREAMING_ERROR', 'STREAMING_ERROR_FIRST_TOKEN_TIMEOUT', 'STREAMING_ERROR_WITH_FALLBACK', 'SYSTEM_ERROR'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='completion_status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'completionstatus', ['SUCCESS', 'USER_ABORTED', 'PROVIDER_ERROR', 'STREAMING_ERROR', 'STREAMING_ERROR_WITH_FALLBACK', 'SYSTEM_ERROR'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='completion_status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
