"""Add indexes for reward_action_log and rewards

Revision ID: 33fca6b92324
Revises: 922c5973705f
Create Date: 2025-01-03 17:54:00.872569+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '33fca6b92324'
down_revision: str | None = '922c5973705f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reward_action_logs_associated_reward_id'), 'reward_action_logs', ['associated_reward_id'], unique=False)
    op.create_index(op.f('ix_reward_action_logs_turn_id'), 'reward_action_logs', ['turn_id'], unique=False)
    op.create_index(op.f('ix_rewards_turn_id'), 'rewards', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewards_turn_id'), table_name='rewards')
    op.drop_index(op.f('ix_reward_action_logs_turn_id'), table_name='reward_action_logs')
    op.drop_index(op.f('ix_reward_action_logs_associated_reward_id'), table_name='reward_action_logs')
    # ### end Alembic commands ###
