"""align model and taxo

Revision ID: bece937e9274
Revises: e17e26f196da
Create Date: 2025-03-06 19:09:25.948647+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'bece937e9274'
down_revision: str | None = 'e17e26f196da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_model_taxonomy', sa.Column('is_reasoning', sa.Boolean(), nullable=True))
    op.add_column('language_model_taxonomy', sa.Column('is_image_generation', sa.Boolean(), nullable=True))
    op.add_column('language_model_taxonomy', sa.Column('external_model_info_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_language_model_taxonomy_is_image_generation'), 'language_model_taxonomy', ['is_image_generation'], unique=False)
    op.create_index(op.f('ix_language_model_taxonomy_is_live'), 'language_model_taxonomy', ['is_live'], unique=False)
    op.create_index(op.f('ix_language_model_taxonomy_is_pro'), 'language_model_taxonomy', ['is_pro'], unique=False)
    op.create_index(op.f('ix_language_model_taxonomy_is_reasoning'), 'language_model_taxonomy', ['is_reasoning'], unique=False)
    op.create_index(op.f('ix_language_model_taxonomy_is_strong'), 'language_model_taxonomy', ['is_strong'], unique=False)
    op.add_column('language_models', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_models', 'priority')
    op.drop_index(op.f('ix_language_model_taxonomy_is_strong'), table_name='language_model_taxonomy')
    op.drop_index(op.f('ix_language_model_taxonomy_is_reasoning'), table_name='language_model_taxonomy')
    op.drop_index(op.f('ix_language_model_taxonomy_is_pro'), table_name='language_model_taxonomy')
    op.drop_index(op.f('ix_language_model_taxonomy_is_live'), table_name='language_model_taxonomy')
    op.drop_index(op.f('ix_language_model_taxonomy_is_image_generation'), table_name='language_model_taxonomy')
    op.drop_column('language_model_taxonomy', 'external_model_info_url')
    op.drop_column('language_model_taxonomy', 'is_image_generation')
    op.drop_column('language_model_taxonomy', 'is_reasoning')
    # ### end Alembic commands ###
