"""add is fast

Revision ID: 559599f84bf8
Revises: ed8457eeb3f4
Create Date: 2025-02-27 22:52:50.105601+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '559599f84bf8'
down_revision: str | None = 'ed8457eeb3f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('is_fast', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'is_fast')
    # ### end Alembic commands ###
