"""populate soul roles

Revision ID: 7847fcfc6d48
Revises: 5e8fbde7c4b7
Create Date: 2025-02-08 16:22:57.626001+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import asyncio
from dotenv import load_dotenv

from ypl.db.oneoffs.populate_soul_rbac import populate_soul_rbac, remove_soul_rbac


# revision identifiers, used by Alembic.
revision: str = '7847fcfc6d48'
down_revision: str | None = '5e8fbde7c4b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    asyncio.run(populate_soul_rbac(connection))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    asyncio.run(remove_soul_rbac(connection))
    # ### end Alembic commands ###
