"""add review note

Revision ID: 266429283b27
Revises: 76e4a795bda8
Create Date: 2025-03-03 18:37:42.609782+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '266429283b27'
down_revision: str | None = '76e4a795bda8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abuse_events', sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abuse_events', 'review_notes')
    # ### end Alembic commands ###
