"""add promptbox placeholder flag to suggestions

Revision ID: 3e6ce97ce0d2
Revises: c28c3a14d16d
Create Date: 2025-02-12 18:57:51.414073+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e6ce97ce0d2'
down_revision: str | None = 'c28c3a14d16d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FOLLOWUP', 'PROMPTBOX_PLACEHOLDER', name='suggestedprompttype').create(op.get_bind())
    op.add_column('suggested_turn_prompts', sa.Column('suggestion_type', postgresql.ENUM('FOLLOWUP', 'PROMPTBOX_PLACEHOLDER', name='suggestedprompttype', create_type=False), server_default='FOLLOWUP', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_turn_prompts', 'suggestion_type')
    sa.Enum('FOLLOWUP', 'PROMPTBOX_PLACEHOLDER', name='suggestedprompttype').drop(op.get_bind())
    # ### end Alembic commands ###
