"""Add MessageUIStatus.DOWNVOTED enum

Revision ID: 470424e1c062
Revises: 64f8e829055e
Create Date: 2025-02-20 23:51:57.864735+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '470424e1c062'
down_revision: str | None = '64f8e829055e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'messageuistatus', ['UNKNOWN', 'SEEN', 'DISMISSED', 'SELECTED', 'DOWNVOTED', 'OBSOLETE'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='ui_status', existing_server_default="'UNKNOWN'::messageuistatus")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'messageuistatus', ['UNKNOWN', 'SEEN', 'DISMISSED', 'SELECTED', 'OBSOLETE'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='ui_status', existing_server_default="'UNKNOWN'::messageuistatus")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
