"""make a cashout entry in the capability table

Revision ID: acf85aaa818d
Revises: dc001c1fc0e7
Create Date: 2025-01-18 02:31:44.640452+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from ypl.db.oneoffs.create_cashout_capability import create_cashout_capability, remove_cashout_capability
# revision identifiers, used by Alembic.
revision: str = 'acf85aaa818d'
down_revision: str | None = 'dc001c1fc0e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_cashout_capability(op.get_bind())
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    remove_cashout_capability(op.get_bind())
    pass
    # ### end Alembic commands ###
