"""add internal only

Revision ID: 320fc8ee45ef
Revises: 601606e02252
Create Date: 2025-02-25 23:02:53.478432+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '320fc8ee45ef'
down_revision: str | None = '601606e02252'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_model_taxonomy', sa.Column('is_internal', sa.Boolean(), nullable=True))
    op.add_column('language_models', sa.Column('is_internal', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_language_models_is_internal'), 'language_models', ['is_internal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_models_is_internal'), table_name='language_models')
    op.drop_column('language_models', 'is_internal')
    op.drop_column('language_model_taxonomy', 'is_internal')
    # ### end Alembic commands ###
