"""add abuse events

Revision ID: 470a249cf9b9
Revises: 1e12a84edb88
Create Date: 2025-02-26 05:36:44.518429+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '470a249cf9b9'
down_revision: str | None = '1e12a84edb88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING_REVIEW', 'REVIEWED', 'CANCELLED', name='abuseeventstate').create(op.get_bind())
    sa.Enum('CASHOUT_SAME_INSTRUMENT_AS_REFERRER', 'CASHOUT_SAME_INSTRUMENT_AS_RECENT_NEW_USER', 'CASHOUT_MULTIPLE_RECENT_REFERRAL_SIGNUPS', name='abuseeventtype').create(op.get_bind())
    op.create_table('abuse_events',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abuse_event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('CASHOUT_SAME_INSTRUMENT_AS_REFERRER', 'CASHOUT_SAME_INSTRUMENT_AS_RECENT_NEW_USER', 'CASHOUT_MULTIPLE_RECENT_REFERRAL_SIGNUPS', name='abuseeventtype', create_type=False), nullable=False),
    sa.Column('event_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', postgresql.ENUM('PENDING_REVIEW', 'REVIEWED', 'CANCELLED', name='abuseeventstate', create_type=False), server_default='PENDING_REVIEW', nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_abuse_events_user_id_users')),
    sa.PrimaryKeyConstraint('abuse_event_id', name=op.f('pk_abuse_events'))
    )
    op.create_index(op.f('ix_abuse_events_user_id'), 'abuse_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abuse_events_user_id'), table_name='abuse_events')
    op.drop_table('abuse_events')
    sa.Enum('CASHOUT_SAME_INSTRUMENT_AS_REFERRER', 'CASHOUT_SAME_INSTRUMENT_AS_RECENT_NEW_USER', 'CASHOUT_MULTIPLE_RECENT_REFERRAL_SIGNUPS', name='abuseeventtype').drop(op.get_bind())
    sa.Enum('PENDING_REVIEW', 'REVIEWED', 'CANCELLED', name='abuseeventstate').drop(op.get_bind())
    # ### end Alembic commands ###
