"""add router selected models to the turn table

Revision ID: 46da6ec47dca
Revises: d32c9d7a3041
Create Date: 2025-02-06 08:52:10.612243+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '46da6ec47dca'
down_revision: str | None = 'd32c9d7a3041'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('router_selected_models', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'router_selected_models')
    # ### end Alembic commands ###
