"""add app feedback quality score

Revision ID: 04673f366c56
Revises: d95e54ceec26
Create Date: 2025-03-05 01:13:29.666259+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '04673f366c56'
down_revision: str | None = 'd95e54ceec26'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_feedback', sa.Column('quality_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_feedback', 'quality_score')
    # ### end Alembic commands ###
