"""add promotions table

Revision ID: b540f1efb7cf
Revises: 257a0fed3c7a
Create Date: 2025-02-04 06:28:46.260070+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b540f1efb7cf'
down_revision: str | None = '257a0fed3c7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_promotions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promotion_id', sa.Uuid(), nullable=False),
    sa.Column('language_model_id', sa.Uuid(), nullable=False),
    sa.Column('in_promo', sa.Boolean(), nullable=False),
    sa.Column('promo_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promo_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promo_strength', sa.Float(), nullable=True),
    sa.CheckConstraint('(promo_start_date IS NULL OR promo_end_date IS NULL) OR promo_end_date > promo_start_date', name=op.f('ck_model_promotions_model_promotions_date_order')),
    sa.CheckConstraint('promo_strength >= 0.0 AND promo_strength <= 1.0', name=op.f('ck_model_promotions_model_promotions_promo_strength_range')),
    sa.ForeignKeyConstraint(['language_model_id'], ['language_models.language_model_id'], name=op.f('fk_model_promotions_language_model_id_language_models')),
    sa.PrimaryKeyConstraint('promotion_id', name=op.f('pk_model_promotions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_promotions')
    # ### end Alembic commands ###
