"""add paypal webhook entry

Revision ID: e48cf5805daa
Revises: e49037cc0a53
Create Date: 2025-02-14 16:57:42.717885+00:00

"""
from collections.abc import Sequence

from alembic import op

from ypl.db.oneoffs.create_paypal_webhook_partner import (
    create_paypal_webhook_partner,
    remove_paypal_webhook_partner,
)


# revision identifiers, used by Alembic.
revision: str = 'e48cf5805daa'
down_revision: str | None = 'e49037cc0a53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    create_paypal_webhook_partner(connection)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    remove_paypal_webhook_partner(connection)
    # ### end Alembic commands ###
