"""add partner reference id to webhook events table

Revision ID: f09a64b1d4b4
Revises: a3f79e7b1932
Create Date: 2025-01-13 13:49:34.076285+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f09a64b1d4b4'
down_revision: str | None = 'a3f79e7b1932'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('partner_webhook_reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'partner_webhook_reference_id')
    # ### end Alembic commands ###
