"""Add cashout_payment_transaction_id index

Revision ID: 6fcd73eab70a
Revises: 81846006ae1c
Create Date: 2025-01-30 14:50:24.387825+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6fcd73eab70a'
down_revision: str | None = '81846006ae1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_point_transactions_cashout_payment_transaction_id'), 'point_transactions', ['cashout_payment_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_transactions_cashout_payment_transaction_id'), table_name='point_transactions')
    # ### end Alembic commands ###
