"""add reasoning

Revision ID: 320dcebcbb66
Revises: 559599f84bf8
Create Date: 2025-02-28 00:42:00.776179+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '320dcebcbb66'
down_revision: str | None = '559599f84bf8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('is_reasoning', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_language_models_is_reasoning'), 'language_models', ['is_reasoning'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_models_is_reasoning'), table_name='language_models')
    op.drop_column('language_models', 'is_reasoning')
    # ### end Alembic commands ###
