"""new lm taxonomy table

Revision ID: 99537bdbb8b8
Revises: b5ec78efad9e
Create Date: 2025-02-18 00:55:27.539248+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99537bdbb8b8'
down_revision: str | None = 'b5ec78efad9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'INACTIVE', name='languagemodeltaxonomystatusenum').create(op.get_bind())
    op.create_table('language_model_taxonomy',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language_model_taxonomy_id', sa.Uuid(), nullable=False),
    sa.Column('is_leaf_node', sa.Boolean(), nullable=True),
    sa.Column('is_pickable', sa.Boolean(), nullable=True),
    sa.Column('taxo_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='languagemodeltaxonomystatusenum', create_type=False), server_default='ACTIVE', nullable=True),
    sa.Column('model_publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_release', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_strong', sa.Boolean(), nullable=True),
    sa.Column('is_pro', sa.Boolean(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('context_window_tokens', sa.Integer(), nullable=True),
    sa.Column('parameter_count', sa.Integer(), nullable=True),
    sa.Column('knowledge_cutoff_date', sa.Date(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supported_attachment_mime_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('language_model_taxonomy_id', name=op.f('pk_language_model_taxonomy'))
    )
    op.create_index(op.f('ix_language_model_taxonomy_language_model_taxonomy_id'), 'language_model_taxonomy', ['language_model_taxonomy_id'], unique=False)
    op.create_index(op.f('ix_language_model_taxonomy_model_class'), 'language_model_taxonomy', ['model_class'], unique=False)
    op.create_index(op.f('ix_language_model_taxonomy_model_family'), 'language_model_taxonomy', ['model_family'], unique=False)
    op.create_index(op.f('ix_language_model_taxonomy_model_publisher'), 'language_model_taxonomy', ['model_publisher'], unique=False)
    op.create_index(op.f('ix_language_model_taxonomy_model_release'), 'language_model_taxonomy', ['model_release'], unique=False)
    op.create_index(op.f('ix_language_model_taxonomy_model_version'), 'language_model_taxonomy', ['model_version'], unique=False)
    op.add_column('language_models', sa.Column('taxonomy_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_language_models_taxonomy_id_language_model_taxonomy'), 'language_models', 'language_model_taxonomy', ['taxonomy_id'], ['language_model_taxonomy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_language_models_taxonomy_id_language_model_taxonomy'), 'language_models', type_='foreignkey')
    op.drop_column('language_models', 'taxonomy_id')
    op.drop_index(op.f('ix_language_model_taxonomy_model_version'), table_name='language_model_taxonomy')
    op.drop_index(op.f('ix_language_model_taxonomy_model_release'), table_name='language_model_taxonomy')
    op.drop_index(op.f('ix_language_model_taxonomy_model_publisher'), table_name='language_model_taxonomy')
    op.drop_index(op.f('ix_language_model_taxonomy_model_family'), table_name='language_model_taxonomy')
    op.drop_index(op.f('ix_language_model_taxonomy_model_class'), table_name='language_model_taxonomy')
    op.drop_index(op.f('ix_language_model_taxonomy_language_model_taxonomy_id'), table_name='language_model_taxonomy')
    op.drop_table('language_model_taxonomy')
    sa.Enum('ACTIVE', 'INACTIVE', name='languagemodeltaxonomystatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
