"""create table to store webhook events

Revision ID: a3f79e7b1932
Revises: 85aad109fb5e
Create Date: 2025-01-13 11:28:50.668976+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3f79e7b1932'
down_revision: str | None = '85aad109fb5e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('INVALID', 'PROCESSED', 'FAILED', name='webhookprocessingstatusenum').create(op.get_bind())
    sa.Enum('INCOMING', 'OUTGOING', name='webhookdirectionenum').create(op.get_bind())
    op.create_table('webhook_events',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_event_id', sa.Uuid(), nullable=False),
    sa.Column('webhook_partner_id', sa.Uuid(), nullable=False),
    sa.Column('direction', postgresql.ENUM('INCOMING', 'OUTGOING', name='webhookdirectionenum', create_type=False), server_default='INCOMING', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', postgresql.ENUM('INVALID', 'PROCESSED', 'FAILED', name='webhookprocessingstatusenum', create_type=False), server_default='INVALID', nullable=False),
    sa.ForeignKeyConstraint(['webhook_partner_id'], ['webhook_partners.webhook_partner_id'], name=op.f('fk_webhook_events_webhook_partner_id_webhook_partners')),
    sa.PrimaryKeyConstraint('webhook_event_id', name=op.f('pk_webhook_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_events')
    sa.Enum('INCOMING', 'OUTGOING', name='webhookdirectionenum').drop(op.get_bind())
    sa.Enum('INVALID', 'PROCESSED', 'FAILED', name='webhookprocessingstatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
