"""add stripe as a vendor

Revision ID: d7c304ca1b88
Revises: 0143644892d6
Create Date: 2025-03-07 17:11:49.939198+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'd7c304ca1b88'
down_revision: str | None = '0143644892d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'vendornameenum', ['HYPERWALLET', 'STRIPE'],
                        [TableReference(table_schema='public', table_name='user_vendor_profiles', column_name='vendor_name')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'vendornameenum', ['HYPERWALLET'],
                        [TableReference(table_schema='public', table_name='user_vendor_profiles', column_name='vendor_name')],
                        enum_values_to_rename=[('STRIPE', 'HYPERWALLET')])
    # ### end Alembic commands ###
