"""Add memory source

Revision ID: d58f9185263e
Revises: e48310bfb2d4
Create Date: 2025-03-10 21:11:42.994785+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd58f9185263e'
down_revision: str | None = 'e48310bfb2d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER_MESSAGE', 'ASSISTANT_MESSAGE', 'CONSOLIDATED_MEMORY', name='memorysource').create(op.get_bind())
    op.add_column('memories', sa.Column('memory_source', postgresql.ENUM('USER_MESSAGE', 'ASSISTANT_MESSAGE', 'CONSOLIDATED_MEMORY', name='memorysource', create_type=False), server_default='USER_MESSAGE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'memory_source')
    sa.Enum('USER_MESSAGE', 'ASSISTANT_MESSAGE', 'CONSOLIDATED_MEMORY', name='memorysource').drop(op.get_bind())
    # ### end Alembic commands ###
