"""add trending topics

Revision ID: 49aafe9640a2
Revises: 6c3ad8510493
Create Date: 2025-03-13 17:21:24.487140+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49aafe9640a2'
down_revision: str | None = '6c3ad8510493'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_topics',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trending_topic_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('trending_topic_id', name=op.f('pk_trending_topics'))
    )
    op.create_table('news_stories',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('news_story_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thumbnail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trending_topic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['trending_topic_id'], ['trending_topics.trending_topic_id'], name=op.f('fk_news_stories_trending_topic_id_trending_topics')),
    sa.PrimaryKeyConstraint('news_story_id', name=op.f('pk_news_stories'))
    )
    op.create_index(op.f('ix_news_stories_trending_topic_id'), 'news_stories', ['trending_topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_stories_trending_topic_id'), table_name='news_stories')
    op.drop_table('news_stories')
    op.drop_table('trending_topics')
    # ### end Alembic commands ###
