"""model probation status

Revision ID: a80425a6f686
Revises: 04673f366c56
Create Date: 2025-03-05 05:32:49.406421+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'a80425a6f686'
down_revision: str | None = '04673f366c56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'languagemodelstatusenum', ['SUBMITTED', 'VERIFIED_PENDING_ACTIVATION', 'REJECTED', 'ACTIVE', 'INACTIVE', 'PROBATION'],
                        [TableReference(table_schema='public', table_name='language_models', column_name='status', existing_server_default="'SUBMITTED'::languagemodelstatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'languagemodelstatusenum', ['SUBMITTED', 'VERIFIED_PENDING_ACTIVATION', 'REJECTED', 'ACTIVE', 'INACTIVE'],
                        [TableReference(table_schema='public', table_name='language_models', column_name='status', existing_server_default="'SUBMITTED'::languagemodelstatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
