"""add device info columns to SIC claims log

Revision ID: 246317c807d4
Revises: d9f40d22c706
Create Date: 2025-01-17 05:31:13.373655+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '246317c807d4'
down_revision: str | None = 'd9f40d22c706'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_invite_code_claim_logs', sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('special_invite_code_claim_logs', sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('special_invite_code_claim_logs', sa.Column('client_device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special_invite_code_claim_logs', 'client_device_info')
    op.drop_column('special_invite_code_claim_logs', 'user_agent')
    op.drop_column('special_invite_code_claim_logs', 'ip_address')
    # ### end Alembic commands ###
