"""add column for indicating llm is real time

Revision ID: 639895bbd129
Revises: b9fa1b4be02e
Create Date: 2025-01-08 21:10:06.656259+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '639895bbd129'
down_revision: str | None = 'b9fa1b4be02e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('is_live', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_language_models_is_live'), 'language_models', ['is_live'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_models_is_live'), table_name='language_models')
    op.drop_column('language_models', 'is_live')
    # ### end Alembic commands ###
