"""added an index on created_at for events table

Revision ID: 13fbfe21fede
Revises: 9e7525a3e1dc
Create Date: 2025-01-21 07:59:25.791388+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '13fbfe21fede'
down_revision: str | None = '9e7525a3e1dc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_created_at', table_name='events')
    # ### end Alembic commands ###
