"""add indexes on turn table

Revision ID: b755c5c77f4a
Revises: 878219f0bca2
Create Date: 2025-01-26 22:59:18.682466+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b755c5c77f4a'
down_revision: str | None = '878219f0bca2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_turns_chat_id'), 'turns', ['chat_id'], unique=False)
    op.create_index(op.f('ix_turns_creator_user_id'), 'turns', ['creator_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_creator_user_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_chat_id'), table_name='turns')
    # ### end Alembic commands ###
