"""add nuggetized in message review

Revision ID: de9a8ad2284b
Revises: 601606e02252
Create Date: 2025-02-26 00:23:15.446414+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference


# revision identifiers, used by Alembic.
revision: str = 'de9a8ad2284b'
down_revision: str | None = '601606e02252'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'reviewtype', ['BINARY', 'CRITIQUE', 'SEGMENTED', 'NUGGETIZED'],
                        [TableReference(table_schema='public', table_name='message_reviews', column_name='review_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'reviewtype', ['BINARY', 'CRITIQUE', 'SEGMENTED'],
                        [TableReference(table_schema='public', table_name='message_reviews', column_name='review_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
