"""create a stripe webhook endpoint

Revision ID: 4bf3d475e901
Revises: 7099ef5abe25
Create Date: 2025-03-10 08:43:38.110695+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from ypl.db.oneoffs.create_stripe_webhook_partner import create_stripe_webhook_partner, remove_stripe_webhook_partner


# revision identifiers, used by Alembic.
revision: str = '4bf3d475e901'
down_revision: str | None = '7099ef5abe25'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    create_stripe_webhook_partner(connection)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    remove_stripe_webhook_partner(connection)
    # ### end Alembic commands ###
