"""backfill usd amount in payment transaction

Revision ID: 5e8fbde7c4b7
Revises: 3c0489632f3e
Create Date: 2025-02-08 03:35:29.843276+00:00

"""
from collections.abc import Sequence
import asyncio
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from dotenv import load_dotenv

from ypl.db.oneoffs.backfill_usd_amounts import backfill_usd_amounts


# revision identifiers, used by Alembic.
revision: str = '5e8fbde7c4b7'
down_revision: str | None = '3c0489632f3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    asyncio.run(backfill_usd_amounts(connection))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
