"""create a source account for hyperwallet

Revision ID: ae0449373987
Revises: bfc5adb4085d
Create Date: 2025-01-28 09:53:10.664558+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from dotenv import load_dotenv

from ypl.db.oneoffs.create_hyperwallet_payment_instrument import add_hyperwallet_source_payment_instrument, remove_hyperwallet_source_payment_instrument


# revision identifiers, used by Alembic.
revision: str = 'ae0449373987'
down_revision: str | None = 'bfc5adb4085d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    add_hyperwallet_source_payment_instrument(connection)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    remove_hyperwallet_source_payment_instrument(connection)
    pass
    # ### end Alembic commands ###
