"""rename primary key in the user capability override table

Revision ID: b4b19de91f89
Revises: acf85aaa818d
Create Date: 2025-01-18 04:28:03.776340+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b4b19de91f89'
down_revision: str | None = 'acf85aaa818d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_capability_overrides', sa.Column('user_capability_override_id', sa.Uuid(), nullable=False))
    op.drop_column('user_capability_overrides', 'user_capability_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_capability_overrides', sa.Column('user_capability_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('user_capability_overrides', 'user_capability_override_id')
    # ### end Alembic commands ###
