"""add conversation starter explanations

Revision ID: b252c46f05d2
Revises: 21e6c2e8d13c
Create Date: 2025-01-29 22:47:02.885234+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b252c46f05d2'
down_revision: str | None = '21e6c2e8d13c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_user_prompts', sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_user_prompts', 'explanation')
    # ### end Alembic commands ###
