"""added more columns to user profiles table

Revision ID: 03f5fcbf980b
Revises: dbc368c9b786
Create Date: 2025-01-27 09:20:43.521700+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03f5fcbf980b'
down_revision: str | None = 'dbc368c9b786'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('INDIVIDUAL', 'BUSINESS', name='profiletypeenum').create(op.get_bind())
    op.add_column('user_profiles', sa.Column('profile_type', postgresql.ENUM('INDIVIDUAL', 'BUSINESS', name='profiletypeenum', create_type=False), nullable=True))
    op.add_column('user_profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('user_profiles', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('state_province', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('postal_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'postal_code')
    op.drop_column('user_profiles', 'state_province')
    op.drop_column('user_profiles', 'address_line2')
    op.drop_column('user_profiles', 'address_line1')
    op.drop_column('user_profiles', 'date_of_birth')
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'first_name')
    op.drop_column('user_profiles', 'profile_type')
    sa.Enum('INDIVIDUAL', 'BUSINESS', name='profiletypeenum').drop(op.get_bind())
    # ### end Alembic commands ###
