"""add required model types

Revision ID: 5aac3fe67c1d
Revises: ffbcc4c27458
Create Date: 2025-02-25 05:50:33.504387+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5aac3fe67c1d'
down_revision: str | None = 'ffbcc4c27458'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('required_models_types', sa.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'required_models_types')
    # ### end Alembic commands ###
