"""Add downvote evaltype for message downvote

Revision ID: 79b2bd75a908
Revises: 175278814f6b
Create Date: 2025-01-09 19:51:53.075861+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '79b2bd75a908'
down_revision: str | None = '175278814f6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'evaltype', ['SLIDER_V0', 'THUMBS_UP_DOWN_V0', 'QUICK_TAKE_SUGGESTION_V0', 'SELECTION', 'ALL_BAD', 'QUICK_TAKE', 'DOWNVOTE'],
                        [TableReference(table_schema='public', table_name='evals', column_name='eval_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'evaltype', ['SLIDER_V0', 'THUMBS_UP_DOWN_V0', 'QUICK_TAKE_SUGGESTION_V0', 'SELECTION', 'ALL_BAD', 'QUICK_TAKE'],
                        [TableReference(table_schema='public', table_name='evals', column_name='eval_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
