"""column to store supported attachment types in language models

Revision ID: f4598010fea5
Revises: f09a64b1d4b4
Create Date: 2025-01-13 09:09:39.488783+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4598010fea5'
down_revision: str | None = 'f09a64b1d4b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('supported_attachment_mime_types', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_models', 'supported_attachment_mime_types')
    # ### end Alembic commands ###
