"""add index to payment instrument identifier

Revision ID: 1e12a84edb88
Revises: 6e2a241ae9a2
Create Date: 2025-02-26 01:54:06.821593+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1e12a84edb88'
down_revision: str | None = '6e2a241ae9a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payment_instruments_identifier'), 'payment_instruments', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_instruments_identifier'), table_name='payment_instruments')
    # ### end Alembic commands ###
