"""image gen

Revision ID: d95e54ceec26
Revises: 266429283b27
Create Date: 2025-03-03 23:24:31.597901+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd95e54ceec26'
down_revision: str | None = '266429283b27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('is_image_generation', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_language_models_is_image_generation'), 'language_models', ['is_image_generation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_models_is_image_generation'), table_name='language_models')
    op.drop_column('language_models', 'is_image_generation')
    # ### end Alembic commands ###
