"""add reward enums for referral bonus

Revision ID: 175278814f6b
Revises: 512da476afc3
Create Date: 2025-01-09 15:50:00.000000+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '175278814f6b'
down_revision: str | None = '512da476afc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_action_logs', sa.Column('referrer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('reward_action_logs', sa.Column('referred_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'EVALUATION', 'QT_EVAL', 'TURN', 'FEEDBACK', 'MODEL_FEEDBACK', 'REFERRAL_BONUS_REFERRED_USER', 'REFERRAL_BONUS_REFERRER'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type'), TableReference(table_schema='public', table_name='reward_amount_rules', column_name='action_type', existing_server_default="'TURN'::rewardactionenum"), TableReference(table_schema='public', table_name='reward_probability_rules', column_name='action_type', existing_server_default="'TURN'::rewardactionenum")],
                        enum_values_to_rename=[])
    op.create_index('uq_reward_action_logs_user_referral_bonus', 'reward_action_logs', ['user_id', 'action_type'], unique=True, postgresql_where=sa.text("action_type = 'REFERRAL_BONUS_REFERRED_USER' AND associated_reward_id IS NOT NULL"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reward_action_logs_user_referral_bonus', table_name='reward_action_logs', postgresql_where=sa.text("action_type = 'REFERRAL_BONUS_REFERRED_USER' AND associated_reward_id IS NOT NULL"))
    op.sync_enum_values('public', 'rewardactionenum', ['SIGN_UP', 'EVALUATION', 'QT_EVAL', 'TURN', 'FEEDBACK', 'MODEL_FEEDBACK'],
                        [TableReference(table_schema='public', table_name='reward_action_logs', column_name='action_type'), TableReference(table_schema='public', table_name='reward_amount_rules', column_name='action_type', existing_server_default="'TURN'::rewardactionenum"), TableReference(table_schema='public', table_name='reward_probability_rules', column_name='action_type', existing_server_default="'TURN'::rewardactionenum")],
                        enum_values_to_rename=[])
    op.drop_column('reward_action_logs', 'referred_user_id')
    op.drop_column('reward_action_logs', 'referrer_id')
    # ### end Alembic commands ###
