"""add title_set_by_user flag to chat

Revision ID: 3c0489632f3e
Revises: 329e464ccf03
Create Date: 2025-02-07 19:03:26.569981+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c0489632f3e'
down_revision: str | None = '329e464ccf03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('title_set_by_user', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'title_set_by_user')
    # ### end Alembic commands ###
