"""create a unique index to avoid duplicate entries

Revision ID: 37ecedcaab1b
Revises: 6ef80282969b
Create Date: 2025-01-14 07:08:23.581875+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '37ecedcaab1b'
down_revision: str | None = '6ef80282969b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_webhook_events_partner_webhook_unique', 'webhook_events', ['webhook_partner_id', 'partner_webhook_reference_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_events_partner_webhook_unique', table_name='webhook_events', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
