"""add suggested prompt tables

Revision ID: 65b477011afb
Revises: 13fbfe21fede
Create Date: 2025-01-23 15:21:10.597933+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '65b477011afb'
down_revision: str | None = '13fbfe21fede'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_user_prompts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suggested_user_prompt_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_suggested_user_prompts_user_id_users')),
    sa.PrimaryKeyConstraint('suggested_user_prompt_id', name=op.f('pk_suggested_user_prompts'))
    )
    op.create_index(op.f('ix_suggested_user_prompts_user_id'), 'suggested_user_prompts', ['user_id'], unique=False)
    op.create_table('suggested_turn_prompts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suggested_turn_prompt_id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], name=op.f('fk_suggested_turn_prompts_turn_id_turns')),
    sa.PrimaryKeyConstraint('suggested_turn_prompt_id', name=op.f('pk_suggested_turn_prompts'))
    )
    op.create_index(op.f('ix_suggested_turn_prompts_turn_id'), 'suggested_turn_prompts', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggested_turn_prompts_turn_id'), table_name='suggested_turn_prompts')
    op.drop_table('suggested_turn_prompts')
    op.drop_index(op.f('ix_suggested_user_prompts_user_id'), table_name='suggested_user_prompts')
    op.drop_table('suggested_user_prompts')
    # ### end Alembic commands ###
