"""backfill profile fields

Revision ID: becebee16b22
Revises: b252c46f05d2
Create Date: 2025-01-30 01:16:09.785425+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from ypl.db.oneoffs.backfill_user_profile_fields import backfill_user_profile_fields


# revision identifiers, used by Alembic.
revision: str = 'becebee16b22'
down_revision: str | None = 'b252c46f05d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Run the backfill
    backfill_user_profile_fields(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
