"""add a pending enum to webhook events

Revision ID: 6ef80282969b
Revises: 25321e91855e
Create Date: 2025-01-14 06:57:41.113772+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '6ef80282969b'
down_revision: str | None = '25321e91855e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'webhookprocessingstatusenum', ['INVALID', 'PROCESSED', 'FAILED', 'PENDING'],
                        [TableReference(table_schema='public', table_name='webhook_events', column_name='processing_status', existing_server_default="'INVALID'::webhookprocessingstatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'webhookprocessingstatusenum', ['INVALID', 'PROCESSED', 'FAILED'],
                        [TableReference(table_schema='public', table_name='webhook_events', column_name='processing_status', existing_server_default="'INVALID'::webhookprocessingstatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
