"""sync db state

Revision ID: 8038ec07c962
Revises: ab35ee12e842
Create Date: 2025-02-23 00:30:34.993463+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8038ec07c962'
down_revision: str | None = 'ab35ee12e842'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_reward_action_logs_user_referral_bonus', 'reward_action_logs', ['user_id', 'action_type'], unique=True, postgresql_where=sa.text("action_type = 'REFERRAL_BONUS_REFERRED_USER' AND associated_reward_id IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reward_action_logs_user_referral_bonus', table_name='reward_action_logs', postgresql_where=sa.text("action_type = 'REFERRAL_BONUS_REFERRED_USER' AND associated_reward_id IS NOT NULL"))
    # ### end Alembic commands ###
