"""initial memory support

Revision ID: 495a50844300
Revises: 26b5869699d0
Create Date: 2025-01-31 02:41:44.067455+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '495a50844300'
down_revision: str | None = '26b5869699d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_models',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_model_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('embedding_model_id', name=op.f('pk_embedding_models'))
    )
    op.create_table('memories',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memory_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory_content', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('embedding_model_id', sa.Uuid(), nullable=True),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('agent_language_model_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['agent_language_model_id'], ['language_models.language_model_id'], name=op.f('fk_memories_agent_language_model_id_language_models')),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['embedding_models.embedding_model_id'], name=op.f('fk_memories_embedding_model_id_embedding_models')),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_messages.message_id'], name=op.f('fk_memories_source_message_id_chat_messages')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_memories_user_id_users')),
    sa.PrimaryKeyConstraint('memory_id', name=op.f('pk_memories'))
    )
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_table('embedding_models')
    # ### end Alembic commands ###
