"""add tabapay as a facilitator

Revision ID: 11b446b72f40
Revises: 3401935f99f2
Create Date: 2025-02-13 15:20:54.933224+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '11b446b72f40'
down_revision: str | None = '3401935f99f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN', 'BINANCE', 'CRYPTO_COM', 'UPI', 'PLAID', 'STRIPE', 'HYPERWALLET', 'CHECKOUT_COM', 'TABAPAY'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN', 'BINANCE', 'CRYPTO_COM', 'UPI', 'PLAID', 'STRIPE', 'HYPERWALLET', 'CHECKOUT_COM'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                        enum_values_to_rename=[('TABAPAY', 'BANK')])
    # ### end Alembic commands ###
