"""create a stripe entry in payment instruments table

Revision ID: e17e26f196da
Revises: 2fb5a430edba
Create Date: 2025-03-06 08:14:49.470696+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from ypl.db.payments import PaymentInstrument, PaymentInstrumentFacilitatorEnum, PaymentInstrumentIdentifierTypeEnum
from ypl.db.oneoffs.create_stripe_payment_instrument import add_stripe_source_payment_instrument, remove_stripe_source_payment_instrument
from dotenv import load_dotenv

# revision identifiers, used by Alembic.
revision: str = 'e17e26f196da'
down_revision: str | None = '2fb5a430edba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    add_stripe_source_payment_instrument(connection)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    remove_stripe_source_payment_instrument(connection)
    pass
    # ### end Alembic commands ###
