"""add tabapay source account

Revision ID: f650d72412a0
Revises: 11b446b72f40
Create Date: 2025-02-13 15:27:01.157524+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from dotenv import load_dotenv

from ypl.db.oneoffs.create_tabapay_payment_instrument import add_tabapay_source_payment_instrument, remove_tabapay_source_payment_instrument


# revision identifiers, used by Alembic.
revision: str = 'f650d72412a0'
down_revision: str | None = '11b446b72f40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    add_tabapay_source_payment_instrument(connection)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    remove_tabapay_source_payment_instrument(connection)
    # ### end Alembic commands ###
