"""add proposal strength

Revision ID: 9504a1a871b4
Revises: 470424e1c062
Create Date: 2025-02-21 18:27:41.018476+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9504a1a871b4'
down_revision: str | None = '470424e1c062'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_promotions', sa.Column('proposal_strength', sa.Float(), nullable=True))
    sa.CheckConstraint('proposal_strength > 0.0', name=op.f('ck_model_promotions_model_promotions_proposal_strength_range')),

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_promotions', 'proposal_strength')
    # ### end Alembic commands ###
