"""add profile information to user table

Revision ID: 30e6ff68983e
Revises: ae0449373987
Create Date: 2025-01-28 20:56:57.250113+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '30e6ff68983e'
down_revision: str | None = 'ae0449373987'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('educational_institution', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('discord_username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_country_code'), 'users', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_country_code'), table_name='users')
    op.drop_column('users', 'discord_username')
    op.drop_column('users', 'city')
    op.drop_column('users', 'country_code')
    op.drop_column('users', 'educational_institution')
    # ### end Alembic commands ###
