"""Add EmailLogs table to store successfully-sent emails

Revision ID: 26b5869699d0
Revises: bfb258fd31d7
Create Date: 2025-01-31 01:43:18.092383+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '26b5869699d0'
down_revision: str | None = 'bfb258fd31d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_log_id', sa.Uuid(), nullable=False),
    sa.Column('email_sent_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('email_log_id', name=op.f('pk_email_logs'))
    )
    op.create_index(op.f('ix_email_logs_email_sent_to'), 'email_logs', ['email_sent_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_email_sent_to'), table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
