"""remove foreign key

Revision ID: e5e9c1cf445d
Revises: 3083d3c6cab5
Create Date: 2025-03-11 20:27:01.111566+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e5e9c1cf445d'
down_revision: str | None = '3083d3c6cab5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_routing_info_turn_id_turns', 'routing_info', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_routing_info_turn_id_turns', 'routing_info', 'turns', ['turn_id'], ['turn_id'])
    # ### end Alembic commands ###
