"""default for points

Revision ID: 41fce37570e0
Revises: 65b477011afb
Create Date: 2025-01-24 02:57:08.744477+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '41fce37570e0'
down_revision: str | None = '65b477011afb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'points', server_default="0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'points', server_default="1000")
    # ### end Alembic commands ###
