"""add routing reasons

Revision ID: e48310bfb2d4
Revises: 1a6ebbca7830
Create Date: 2025-03-10 19:53:58.634818+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e48310bfb2d4'
down_revision: str | None = '1a6ebbca7830'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_reasons',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('routing_reason_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('routing_reason_id', 'reason', name=op.f('pk_routing_reasons'))
    )
    op.create_index(op.f('ix_routing_reasons_is_active'), 'routing_reasons', ['is_active'], unique=False)
    op.create_index(op.f('ix_routing_reasons_reason'), 'routing_reasons', ['reason'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routing_reasons_reason'), table_name='routing_reasons')
    op.drop_index(op.f('ix_routing_reasons_is_active'), table_name='routing_reasons')
    op.drop_table('routing_reasons')
    # ### end Alembic commands ###
