"""column to check streaming status

Revision ID: 7099ef5abe25
Revises: 6ee07e7d9ab9
Create Date: 2025-03-09 15:20:45.847488+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7099ef5abe25'
down_revision: str | None = '6ee07e7d9ab9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_models', sa.Column('is_streaming_supported', sa.Boolean(), server_default='TRUE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_models', 'is_streaming_supported')
    # ### end Alembic commands ###
