"""add LM tier

Revision ID: cc6d8bf497a0
Revises: 812ef1a5b53a
Create Date: 2025-03-13 01:42:21.120514+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc6d8bf497a0'
down_revision: str | None = '812ef1a5b53a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PICKER_ONLY', 'ROUTER_ONLY', 'PICKER_AND_ROUTER', name='languagemodeltierenum').create(op.get_bind())
    op.add_column('language_model_taxonomy', sa.Column('tier', postgresql.ENUM('PICKER_ONLY', 'ROUTER_ONLY', 'PICKER_AND_ROUTER', name='languagemodeltierenum', create_type=False), server_default='PICKER_AND_ROUTER', nullable=True))
    op.add_column('language_models', sa.Column('tier', postgresql.ENUM('PICKER_ONLY', 'ROUTER_ONLY', 'PICKER_AND_ROUTER', name='languagemodeltierenum', create_type=False), server_default='PICKER_AND_ROUTER', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_models', 'tier')
    op.drop_column('language_model_taxonomy', 'tier')
    sa.Enum('PICKER_ONLY', 'ROUTER_ONLY', 'PICKER_AND_ROUTER', name='languagemodeltierenum').drop(op.get_bind())
    # ### end Alembic commands ###
