"""created a new events table

Revision ID: 846c04ab16be
Revises: b4b19de91f89
Create Date: 2025-01-20 03:47:24.262416+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '846c04ab16be'
down_revision: str | None = 'b4b19de91f89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_guestivity_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_dedup_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_events_user_id_users')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_event_category'), 'events', ['event_category'], unique=False)
    op.create_index(op.f('ix_events_event_dedup_id'), 'events', ['event_dedup_id'], unique=False)
    op.create_index(op.f('ix_events_event_name'), 'events', ['event_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_event_name'), table_name='events')
    op.drop_index(op.f('ix_events_event_dedup_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_category'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
