"""Add destination_identifier index

Revision ID: 81846006ae1c
Revises: becebee16b22
Create Date: 2025-01-30 13:57:52.827321+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '81846006ae1c'
down_revision: str | None = 'becebee16b22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payment_transactions_destination_instrument_id'), 'payment_transactions', ['destination_instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transactions_destination_instrument_id'), table_name='payment_transactions')
    # ### end Alembic commands ###
