"""create a naughty list table

Revision ID: 250d95133d8f
Revises: 470a249cf9b9
Create Date: 2025-02-26 05:49:19.195477+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '250d95133d8f'
down_revision: str | None = '470a249cf9b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'INACTIVE', name='statusenum').create(op.get_bind())
    sa.Enum('IP_ADDRESS', 'DOMAIN', 'EMAIL', 'USERNAME', 'OTHER', name='entitytypeenum').create(op.get_bind())
    op.create_table('naughtylist',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('naughtylist_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('entity_type', postgresql.ENUM('IP_ADDRESS', 'DOMAIN', 'EMAIL', 'USERNAME', 'OTHER', name='entitytypeenum', create_type=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='statusenum', create_type=False), server_default='ACTIVE', nullable=False),
    sa.Column('added_by_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.user_id'], name=op.f('fk_naughtylist_added_by_user_id_users')),
    sa.PrimaryKeyConstraint('naughtylist_id', name=op.f('pk_naughtylist')),
    sa.UniqueConstraint('entity_type', 'value', name='uq_naughtylist_entity_type_value')
    )
    op.create_index(op.f('ix_naughtylist_value'), 'naughtylist', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_naughtylist_value'), table_name='naughtylist')
    op.drop_table('naughtylist')
    sa.Enum('IP_ADDRESS', 'DOMAIN', 'EMAIL', 'USERNAME', 'OTHER', name='entitytypeenum').drop(op.get_bind())
    sa.Enum('ACTIVE', 'INACTIVE', name='statusenum').drop(op.get_bind())
    # ### end Alembic commands ###
