"""added an enum for new payment facilitator type

Revision ID: bfc5adb4085d
Revises: 22caba87cd15
Create Date: 2025-01-28 09:43:16.957606+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'bfc5adb4085d'
down_revision: str | None = '22caba87cd15'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN', 'BINANCE', 'CRYPTO_COM', 'UPI', 'PLAID', 'STRIPE', 'HYPERWALLET'],
                       [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', 
                       ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN', 'BINANCE', 'CRYPTO_COM', 'UPI', 'PLAID', 'STRIPE'],
                       [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                       enum_values_to_rename=[('HYPERWALLET', 'BANK')])
    # ### end Alembic commands ###
