"""add coinbase retail source account

Revision ID: 922c5973705f
Revises: 775fff998f1d
Create Date: 2025-01-01 03:40:19.124193+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from dotenv import load_dotenv

from ypl.db.oneoffs.create_coinbase_payment_instrument import add_coinbase_retail_wallet_payment_instrument, remove_coinbase_retail_wallet_payment_instrument


# revision identifiers, used by Alembic.
revision: str = '922c5973705f'
down_revision: str | None = '775fff998f1d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    add_coinbase_retail_wallet_payment_instrument(connection)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_dotenv()
    connection = op.get_bind()
    remove_coinbase_retail_wallet_payment_instrument(connection)
    pass
    # ### end Alembic commands ###
