"""add waitlist use limit

Revision ID: e2da284f9c7d
Revises: bc7531a08c67
Create Date: 2025-01-07 21:34:30.710557+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e2da284f9c7d'
down_revision: str | None = 'bc7531a08c67'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_invite_codes', sa.Column('usage_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special_invite_codes', 'usage_limit')
    # ### end Alembic commands ###
