"""added a vendor name column to indicate which vendor the row is for

Revision ID: 83a11cd75146
Revises: 03f5fcbf980b
Create Date: 2025-01-27 09:31:55.759166+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83a11cd75146'
down_revision: str | None = '03f5fcbf980b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('HYPERWALLET', name='vendornameenum').create(op.get_bind())
    op.add_column('user_vendor_profiles', sa.Column('vendor_name', postgresql.ENUM('HYPERWALLET', name='vendornameenum', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_vendor_profiles', 'vendor_name')
    sa.Enum('HYPERWALLET', name='vendornameenum').drop(op.get_bind())
    # ### end Alembic commands ###
