"""added metadata to payment instrument

Revision ID: a71fbb0ab222
Revises: f1effd1ce1ef
Create Date: 2025-01-06 14:48:00.835416+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a71fbb0ab222'
down_revision: str | None = 'f1effd1ce1ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_instruments', sa.Column('instrument_metadata', JSONB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_instruments', 'instrument_metadata')
    # ### end Alembic commands ###
