"""create column to capture reversed txn id

Revision ID: 64f8e829055e
Revises: fa000711d503
Create Date: 2025-02-19 15:14:57.037369+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '64f8e829055e'
down_revision: str | None = 'fa000711d503'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_transactions', sa.Column('reversed_transaction_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_point_transactions_reversed_transaction_id'), 'point_transactions', ['reversed_transaction_id'], unique=False)
    op.create_foreign_key(op.f('fk_point_transactions_reversed_transaction_id_point_transactions'), 'point_transactions', 'point_transactions', ['reversed_transaction_id'], ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_point_transactions_reversed_transaction_id_point_transactions'), 'point_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_point_transactions_reversed_transaction_id'), table_name='point_transactions')
    op.drop_column('point_transactions', 'reversed_transaction_id')
    # ### end Alembic commands ###
