"""create a webhook entry for coinbase

Revision ID: 512da476afc3
Revises: 472249288b96
Create Date: 2025-01-09 15:49:34.568423+00:00

"""
from collections.abc import Sequence

from alembic import op

from ypl.db.oneoffs.create_coinbase_webhook_partner import create_coinbase_webhook_partner
from ypl.db.oneoffs.create_coinbase_webhook_partner import remove_coinbase_webhook_partner

# revision identifiers, used by Alembic.
revision: str = '512da476afc3'
down_revision: str | None = '472249288b96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    create_coinbase_webhook_partner(connection)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    remove_coinbase_webhook_partner(connection)
    # ### end Alembic commands ###
