"""adding chat instrumentation table

Revision ID: f506d37928ad
Revises: 250d95133d8f
Create Date: 2025-02-26 07:10:30.013236+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f506d37928ad'
down_revision: str | None = '250d95133d8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_instrumentations',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('head_client', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('head_server', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mind_server', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_status', sa.Text(), nullable=True),
    sa.Column('analysis_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], name=op.f('fk_chat_instrumentations_message_id_chat_messages')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_chat_instrumentations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_instrumentations')
    # ### end Alembic commands ###
