"""Add suggestion click annotations

Revision ID: 812ef1a5b53a
Revises: c3135a12bfd5
Create Date: 2025-03-11 23:37:20.252085+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '812ef1a5b53a'
down_revision: str | None = 'c3135a12bfd5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turn_qualities', sa.Column('is_suggested_followup', sa.Boolean(), nullable=True))
    op.add_column('turn_qualities', sa.Column('is_conversation_starter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turn_qualities', 'is_conversation_starter')
    op.drop_column('turn_qualities', 'is_suggested_followup')
    # ### end Alembic commands ###
