"""add hidden ui status

Revision ID: fa000711d503
Revises: 996d3b884f49
Create Date: 2025-02-18 23:55:05.001022+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa000711d503'
down_revision: str | None = '996d3b884f49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'messageuistatus', ['UNKNOWN', 'SEEN', 'DISMISSED', 'SELECTED', 'OBSOLETE'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='ui_status', existing_server_default="'UNKNOWN'::messageuistatus")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'messageuistatus', ['UNKNOWN', 'SEEN', 'DISMISSED', 'SELECTED'],
                        [TableReference(table_schema='public', table_name='chat_messages', column_name='ui_status', existing_server_default="'UNKNOWN'::messageuistatus")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
