"""Add additional_info and cust ref ID fields

Revision ID: bc7531a08c67
Revises: 3dc92077600f
Create Date: 2025-01-07 17:18:16.105016+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc7531a08c67'
down_revision: str | None = '3dc92077600f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('payment_transactions', sa.Column('customer_reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'customer_reference_id')
    op.drop_column('payment_transactions', 'additional_info')
    # ### end Alembic commands ###
