"""update user profile table

Revision ID: 25321e91855e
Revises: dfe9ccb21287
Create Date: 2025-01-14 03:02:09.937341+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '25321e91855e'
down_revision: str | None = 'dfe9ccb21287'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'educational_institution',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('user_profiles', 'discord_username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_profiles_country'), 'user_profiles', ['country'], unique=False)
    op.drop_constraint("country_iso_alpha2_check", "user_profiles", type_="check")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "country_iso_alpha2_check",
        "user_profiles",
        "country ~ '^[A-Z]{2}$'"
    )
    op.drop_index(op.f('ix_user_profiles_country'), table_name='user_profiles')
    op.alter_column('user_profiles', 'discord_username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'country',
               existing_type=sa.String(length=2),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'educational_institution',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
