"""Add UserStatus to users table

Revision ID: d9f40d22c706
Revises: 37ecedcaab1b
Create Date: 2025-01-14 22:19:03.526345+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9f40d22c706'
down_revision: str | None = '37ecedcaab1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'DEACTIVATED', name='userstatus').create(op.get_bind())
    op.add_column('users', sa.Column('status', postgresql.ENUM('ACTIVE', 'DEACTIVATED', name='userstatus', create_type=False), server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    sa.Enum('ACTIVE', 'DEACTIVATED', name='userstatus').drop(op.get_bind())
    # ### end Alembic commands ###
