"""add yapps table

Revision ID: 417e7bbc0848
Revises: 0b1ce165c3d4
Create Date: 2025-02-12 01:18:19.601322+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '417e7bbc0848'
down_revision: str | None = '0b1ce165c3d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yapps',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yapp_id', sa.Uuid(), nullable=False),
    sa.Column('language_model_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['language_model_id'], ['language_models.language_model_id'], name=op.f('fk_yapps_language_model_id_language_models')),
    sa.PrimaryKeyConstraint('yapp_id', name=op.f('pk_yapps'))
    )
    op.create_index(op.f('ix_yapps_language_model_id'), 'yapps', ['language_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yapps_language_model_id'), table_name='yapps')
    op.drop_table('yapps')
    # ### end Alembic commands ###
