"""Add a column to indicate if a special invite code is eligible for referral bonus.

Revision ID: fc9f4f641792
Revises: e48cf5805daa
Create Date: 2025-02-14 16:58:42.717885+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fc9f4f641792'
down_revision: str | None = 'e48cf5805daa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_invite_codes', sa.Column('referral_bonus_eligible', sa.Boolean(), nullable=False, server_default=sa.text("TRUE")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special_invite_codes', 'referral_bonus_eligible')
    # ### end Alembic commands ###
