"""add stripe as a facilitator

Revision ID: 8e7d121fda22
Revises: 246317c807d4
Create Date: 2025-01-17 11:28:04.290829+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '8e7d121fda22'
down_revision: str | None = '246317c807d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN', 'BINANCE', 'CRYPTO_COM', 'UPI', 'PLAID', 'STRIPE'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'paymentinstrumentfacilitatorenum', ['BANK', 'COINBASE', 'PAYPAL', 'ON_CHAIN', 'BINANCE', 'CRYPTO_COM', 'UPI', 'PLAID'],
                        [TableReference(table_schema='public', table_name='payment_instruments', column_name='facilitator')],
                        enum_values_to_rename=[('STRIPE', 'BANK')])
    # ### end Alembic commands ###
