"""add trending topic convo starters

Revision ID: 13a23eed2cd7
Revises: 49aafe9640a2
Create Date: 2025-03-13 19:12:30.006856+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '13a23eed2cd7'
down_revision: str | None = '49aafe9640a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_trending_topic_prompts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suggested_trending_topic_prompt_id', sa.Uuid(), nullable=False),
    sa.Column('trending_topic_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['trending_topic_id'], ['trending_topics.trending_topic_id'], name=op.f('fk_suggested_trending_topic_prompts_trending_topic_id_trending_topics')),
    sa.PrimaryKeyConstraint('suggested_trending_topic_prompt_id', name=op.f('pk_suggested_trending_topic_prompts'))
    )
    op.create_index(op.f('ix_suggested_trending_topic_prompts_trending_topic_id'), 'suggested_trending_topic_prompts', ['trending_topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggested_trending_topic_prompts_trending_topic_id'), table_name='suggested_trending_topic_prompts')
    op.drop_table('suggested_trending_topic_prompts')
    # ### end Alembic commands ###
