"""initial schema for chat

Revision ID: 04c8093a862b
Revises: 
Create Date: 2024-08-09 17:54:11.477505+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04c8093a862b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CHAT_MESSAGE', 'USER_MESSAGE', 'ASSISTANT_MESSAGE', name='messagetype').create(op.get_bind())
    op.create_table('chats',
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_chats_path'), 'chats', ['path'], unique=True)
    op.create_table('turns',
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.PrimaryKeyConstraint('turn_id'),
    sa.UniqueConstraint('chat_id', 'sequence_id', name='uq_chat_sequence')
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('message_type', postgresql.ENUM('CHAT_MESSAGE', 'USER_MESSAGE', 'ASSISTANT_MESSAGE', name='messagetype', create_type=False), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assistant_model_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('turns')
    op.drop_index(op.f('ix_chats_path'), table_name='chats')
    op.drop_table('chats')
    sa.Enum('CHAT_MESSAGE', 'USER_MESSAGE', 'ASSISTANT_MESSAGE', name='messagetype').drop(op.get_bind())
    # ### end Alembic commands ###
