from ypl.db import (
    app_feedback,
    attachments,
    chats,
    emails,
    embeddings,
    events,
    invite_codes,
    language_models,
    memories,
    model_promotions,
    payments,
    point_transactions,
    ratings,
    rewards,
    soul_rbac,
    users,
    webhooks,
    yapps,
)

all_models = [
    # Please keep sorted.
    app_feedback,
    attachments,
    chats,
    emails,
    embeddings,
    events,
    invite_codes,
    language_models,
    memories,
    payments,
    point_transactions,
    model_promotions,
    ratings,
    rewards,
    soul_rbac,
    users,
    webhooks,
    yapps,
]
