name: Build and Push Embedding Server Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ypl/embeddings/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/embeddings_server:latest

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: embeddings_server_image
          path: |
            $(docker save ghcr.io/${{ github.repository }}/embeddings_server:latest)
          compression-level: 9
          if-no-files-found: error
