name: Build and Deploy

on:
  push:
    branches: [ staging ]
  schedule:
    - cron: '0 9,21 * * *'  # Runs at 9 AM/PM UTC (2 AM/PM PST) daily
  workflow_dispatch:
    inputs:
      use_prompt_conditional_routing:
        description: 'Whether to use prompt-conditional routing'
        required: true
        default: true
        type: boolean
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      image:
        description: 'Image to deploy'
        required: true
        default: 'backend'
        type: choice
        options:
        - backend
        - backend-pytorch-service
        - backend-pytorch-service-bleeding
      region:
        description: 'Region to deploy to'
        required: true
        default: 'us-east4'
        type: choice
        options:
        - us-east4
        - us-central1
      gpu:
        description: 'Whether to deploy with GPU'
        required: true
        default: 'false'
        type: boolean
      categorizer_model_path:
        description: 'Path to the categorizer model'
        required: true
        default: 'gs://yupp-models/category-model-multilabel-base.zip'
        type: string
      pytorch_serve_gcp_url:
        description: 'URL of the PyTorch Serve GCP service'
        required: true
        default: 'https://backend-pytorch-service-bleeding-staging-451082535721.us-central1.run.app/api/v1'
        type: string


env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ${{ github.event.inputs.image || 'backend' }}
  IMAGE_NAME: "gcr.io/yupp-llms/${{ github.event.inputs.image || 'backend' }}-${{ github.event.inputs.environment || 'staging' }}:v1"
  REGION: ${{ github.event.inputs.region || 'us-east4' }}

permissions:
  contents: write  # Permission required for pushing new tags.
  packages: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Remove unused content on github runners.
    - name: Free up space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up environment
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.environment }}" == "production" ]]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "SERVICE_NAME=${{ github.event.inputs.image || 'backend' }}" >> $GITHUB_ENV
          echo "MEMORY=24Gi" >> $GITHUB_ENV
          echo "CPU=6" >> $GITHUB_ENV
          echo "CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONNECTION_NAME_PRODUCTION }}" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "SERVICE_NAME=${{ github.event.inputs.image || 'backend' }}-staging" >> $GITHUB_ENV
          echo "MEMORY=24Gi" >> $GITHUB_ENV
          echo "CPU=6" >> $GITHUB_ENV
          echo "CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONNECTION_NAME_STAGING }}" >> $GITHUB_ENV
        fi

        if [[ "${{ github.event.inputs.image }}" == "backend-pytorch-service" || "${{ github.event.inputs.image }}" == "backend-pytorch-service-bleeding" ]]; then
          echo "DOCKERFILE=Dockerfile.pytorch-service" >> $GITHUB_ENV
        else
          echo "DOCKERFILE=Dockerfile" >> $GITHUB_ENV
        fi


    - name: Create .env file
      run: |
        echo "ENVIRONMENT=${{ env.ENVIRONMENT }}" >> .env
        echo "PROJECT_NAME=\"Yupp-Server\" " >> .env
        echo "NLTK_DATA=\"data/nltk_data\" " >> .env
        echo "BACKEND_CORS_ORIGINS=${{ env.BACKEND_CORS_ORIGINS }}" >> .env
        echo "X_API_KEY=${{ secrets.X_API_KEY }}" >> .env
        echo "PYTORCH_SERVE_GCP_URL='${{ github.event.inputs.pytorch_serve_gcp_url || 'https://backend-pytorch-service-bleeding-staging-451082535721.us-central1.run.app/api/v1' }}'" >> .env
        echo "CATEGORIZER_MODEL_PATH=${{ github.events.inputs.categorizer_model_path || 'gs://yupp-models/category-model-multilabel-base.zip' }}" >> .env
        echo "ROUTING_USE_PROMPT_CONDITIONAL=${{ github.event.inputs.use_prompt_conditional_routing || 'true' }}" >> .env
        echo "ROUTING_WEIGHTS='{\"random\": 0.1, \"top\": 0.7, \"min_simple_cost\": 0.2}'" >> .env
        echo "ROUTING_GOOD_MODELS_ALWAYS=True" >> .env
        echo "USE_GOOGLE_CLOUD_LOGGING=True" >> .env
        if [[ "${{ env.ENVIRONMENT }}" == "production" ]]; then
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_PRODUCTION }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST_PRODUCTION }}" >> .env
          echo "POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}" >> .env
          echo "POSTGRES_HOST_NON_POOLING=${{ secrets.POSTGRES_HOST_NON_POOLING_PRODUCTION }}" >> .env
          echo "CLOUD_SQL_PROXY_INSTANCE_UNIX_SOCKET=${{ secrets.CLOUD_SQL_PROXY_INSTANCE_UNIX_SOCKET_PRODUCTION }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_PRODUCTION }}" >> .env
          echo "AMPLITUDE_API_KEY=${{ secrets.AMPLITUDE_API_KEY_PRODUCTION }}" >> .env
          echo "AMPLITUDE_API_SECRET=${{ secrets.AMPLITUDE_API_SECRET_PRODUCTION }}" >> .env
          echo "ALIBABA_API_KEY=${{ secrets.ALIBABA_API_KEY_PRODUCTION }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY_PRODUCTION }}" >> .env
          echo "ANYSCALE_API_KEY=${{ secrets.ANYSCALE_API_KEY_PRODUCTION }}" >> .env
          echo "AZURE_API_KEY=${{ secrets.AZURE_API_KEY_PRODUCTION }}" >> .env
          echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY_PRODUCTION }}" >> .env
          echo "FIREWORKS_API_KEY=${{ secrets.FIREWORKS_API_KEY_PRODUCTION }}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY_PRODUCTION }}" >> .env
          echo "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY_PRODUCTION }}" >> .env
          echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY_PRODUCTION }}" >> .env
          echo "NVIDIA_API_KEY=${{ secrets.NVIDIA_API_KEY_PRODUCTION }}" >> .env
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY_PRODUCTION }}" >> .env
          echo "PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY_PRODUCTION }}" >> .env
          echo "TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY_PRODUCTION }}" >> .env
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_PRODUCTION }}" >> .env
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN_PRODUCTION }}" >> .env
          echo "TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY_PRODUCTION }}" >> .env
          echo "TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET_PRODUCTION }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN_PRODUCTION }}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET_PRODUCTION }}" >> .env
        elif [[ "${{ env.ENVIRONMENT }}" == "staging" ]]; then
          echo "OPENAI_API_KEY_ROUTING=${{ secrets.OPENAI_API_KEY_ROUTING }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER_STAGING }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_STAGING }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST_STAGING }}" >> .env
          echo "POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE_STAGING }}" >> .env
          echo "POSTGRES_HOST_NON_POOLING=${{ secrets.POSTGRES_HOST_NON_POOLING_STAGING }}" >> .env
          echo "CLOUD_SQL_PROXY_INSTANCE_UNIX_SOCKET=${{ secrets.CLOUD_SQL_PROXY_INSTANCE_UNIX_SOCKET_STAGING }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_STAGING }}" >> .env
          echo "ALIBABA_API_KEY=${{ secrets.ALIBABA_API_KEY_STAGING }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY_STAGING }}" >> .env
          echo "ANYSCALE_API_KEY=${{ secrets.ANYSCALE_API_KEY_STAGING }}" >> .env
          echo "AZURE_API_KEY=${{ secrets.AZURE_API_KEY_STAGING }}" >> .env
          echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY_STAGING }}" >> .env
          echo "FIREWORKS_API_KEY=${{ secrets.FIREWORKS_API_KEY_STAGING }}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY_STAGING }}" >> .env
          echo "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY_STAGING }}" >> .env
          echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY_STAGING }}" >> .env
          echo "NVIDIA_API_KEY=${{ secrets.NVIDIA_API_KEY_STAGING }}" >> .env
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY_STAGING }}" >> .env
          echo "PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY_STAGING }}" >> .env
          echo "TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY_STAGING }}" >> .env
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_STAGING }}" >> .env
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN_STAGING }}" >> .env
          echo "TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY_STAGING }}" >> .env
          echo "TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET_STAGING }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN_STAGING }}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET_STAGING }}" >> .env
        fi

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Authenticate Docker
      run: gcloud auth configure-docker --quiet

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ env.IMAGE_NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ${{ env.DOCKERFILE }}

    - name: Install gcloud beta
      run: gcloud components install beta

    - name: Deploy to Cloud Run
      run: |
        if [[ "${{ github.event.inputs.gpu }}" == "true" ]]; then
          gcloud beta run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --cpu ${{ env.CPU }} \
            --memory ${{ env.MEMORY }} \
            --gpu-type nvidia-l4 \
            --gpu 1 \
            --service-min-instances 1 \
            --args=service \
            --no-cpu-throttling \
            --add-cloudsql-instances=${{ env.CLOUD_SQL_CONNECTION_NAME }} \
            --command="/app/ypl/pytorch/serve/entrypoint.sh"
        else
          gcloud beta run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --cpu ${{ env.CPU }} \
            --memory ${{ env.MEMORY }} \
            --args=service \
            --add-cloudsql-instances=${{ env.CLOUD_SQL_CONNECTION_NAME }} \
            --command="/app/ypl/backend/entrypoint.sh"
        fi

    - name: Tag commit
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git tag -f latest-${{ github.event.inputs.environment || 'staging' }} ${{ github.sha }}
        git push origin latest-${{ github.event.inputs.environment || 'staging' }} --force

    - name: Post to Slack for Production Deployment
      if: env.ENVIRONMENT == 'production'
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "text": "New backend service version deployed to production",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "New backend service version deployed to production"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PRODUCTION }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
