name: Deploy Staging on DB Migration

on:
  workflow_dispatch:

  push:
    paths:
      - 'ypl/db/alembic/**'
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Trigger deploy workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              repo: 'yupp-mind',
              owner: 'yupp-ai',
              workflow_id: 'deploy.yml',
              ref: 'staging',
              inputs: {
                environment: 'staging',
              }
            });