name: Generate invite codes based on criteria

on:
  schedule:
    - cron: '0 21 * * *'  # Runs at 9 PM UTC / 1PM PST / 2PM PDT every day
  workflow_dispatch:
    inputs:
        environment:
          description: 'Environment to generate invite codes in'
          required: true
          default: 'staging'
          type: choice
          options:
          - staging
          - production
        min_age_days:
          description: 'Minimum age in days for eligible users'
          required: true
          default: '7'
          type: string
        min_eval_days:
          description: 'Minimum number of evaluation days'
          required: true
          default: '2'
          type: string
        min_feedback_count:
          description: 'Minimum number of feedbacks required'
          required: false
          default: '0'
          type: string
        limit:
          description: 'Maximum number of users to generate codes for'
          required: true
          default: '30'
          type: string
        default_active:
          description: 'Whether generated codes should be enabled'
          required: false
          default: true
          type: boolean

jobs:
  generate_invite_codes_for_top_users:
    uses: ./.github/workflows/cronjob.yml
    with:
      command: generate-invite-codes-for-top-users
      args: >-
        --min-age-days=${{ inputs.min_age_days || '7' }}
        --min-eval-days=${{ inputs.min_eval_days || '2' }}
        --min-feedback-count=${{ inputs.min_feedback_count || '0' }}
        --limit=${{ inputs.limit || '30' }}
        ${{ github.event_name == 'workflow_dispatch' && !inputs.default_active && '' || ' --default-active' }}
      environment: ${{ inputs.environment || 'production' }}
    secrets: inherit