name: LLM Monitor Cronjob

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  monitor_llm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore LLM Monitor Log Cache
        uses: actions/cache@v4
        id: cache-restore
        continue-on-error: true
        with:
          path: llm-monitor-log/
          key: llm-monitor-log

      - name: Ensure log directory exists
        run: mkdir -p ./llm-monitor-log

      - name: Run LLM monitor script with secrets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_PRODUCTION }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY_PRODUCTION }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY_PRODUCTION }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY_PRODUCTION }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY_PRODUCTION }}
          TOGETHERAI_API_KEY: ${{ secrets.TOGETHERAI_API_KEY_PRODUCTION }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY_PRODUCTION }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY_PRODUCTION }}
          SLACK_MODEL_MANAGEMENT_APP_BOT_TOKEN: ${{ secrets.SLACK_MODEL_MANAGEMENT_APP_BOT_TOKEN_PRODUCTION }}
        run: |
          chmod +x ./scripts/llm-monitor.sh
          ./scripts/llm-monitor.sh ./llm-monitor-log

      - name: Save LLM Monitor Log Cache
        uses: actions/cache@v4
        with:
          path: llm-monitor-log/
          key: llm-monitor-log
