name: Rollback to previous revision

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback in'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: backend-staging
  REGION: us-east4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
          echo "SERVICE_NAME=backend" >> $GITHUB_ENV
        fi

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Rollback to previous revision
      run: |
        PREVIOUS_REVISION=$(gcloud run revisions list --service=${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --platform=managed --format='value(metadata.name)' --limit=2 | sed -n '2p')
        gcloud run services update-traffic ${{ env.SERVICE_NAME }} \
          --to-revisions=$PREVIOUS_REVISION=100 \
          --region=${{ env.REGION }} \
          --platform=managed
