name: Update ranking

on:
  schedule:
    - cron: '15 0 * * *'  # Daily at 15 minutes past midnight.
  workflow_dispatch:

jobs:
  update_rankings_staging:
    uses: ./.github/workflows/cronjob.yml
    with:
      command: update-ranking-all-categories
      environment: staging
    secrets: inherit

  update_rankings_production:
    uses: ./.github/workflows/cronjob.yml
    with:
      command: update-ranking-all-categories
      environment: production
    secrets: inherit