name: Validate Active Models

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:

jobs:
  validate_active_models_production:
    uses: ./.github/workflows/cronjob.yml
    with:
      command: validate-active-models
      environment: production
    secrets: inherit
